import type { StateBank, Topic } from "./types";

const questions: Array<{
  id: string;
  stateCode: string;
  topic: Topic;
  difficulty: 1 | 2 | 3;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  rule: string;
  tip: string;
}> = [
  {
    id: "ca_001",
    stateCode: "CA",
    topic: "traffic_signs",
    difficulty: 1,
    question: "What does a red octagon sign always mean?",
    options: [
      "Slow down and yield to cross traffic",
      "Stop completely before proceeding",
      "Road construction or detour ahead",
      "Do not enter from this direction",
    ],
    correctIndex: 1,
    explanation: "A red octagon is used for STOP signs and requires a full stop. You must stop at the limit line, before the crosswalk, or before entering the intersection if no line or crosswalk is present.",
    rule: "CVC 22450 - Stop Requirements",
    tip: "Eight sides means stop every time, even if the sign is partly faded.",
  },
  {
    id: "ca_002",
    stateCode: "CA",
    topic: "traffic_signs",
    difficulty: 1,
    question: "At a steady red traffic signal, what must a driver do before turning right when turns are allowed?",
    options: [
      "Slow down and turn if there is a gap",
      "Stop first, then yield to pedestrians and traffic",
      "Turn only after another driver waves you through",
      "Wait for a green arrow even if there is no sign",
    ],
    correctIndex: 1,
    explanation: "A steady red signal requires a stop before entering the intersection. A right turn may be made only after stopping and yielding, unless a sign prohibits the turn.",
    rule: "CVC 21453 - Red Traffic Signals",
    tip: "Red first means stop first; the turn comes after the pause and the yield.",
  },
  {
    id: "ca_003",
    stateCode: "CA",
    topic: "traffic_signs",
    difficulty: 2,
    question: "What should you do when you approach a flashing red traffic signal?",
    options: [
      "Treat it like a stop sign and proceed when safe",
      "Continue through if cross traffic has a flashing yellow",
      "Stop only if another vehicle is already in the intersection",
      "Slow to 15 mph and keep moving",
    ],
    correctIndex: 0,
    explanation: "A flashing red signal means you must stop. After stopping, you may proceed only when the movement can be made safely.",
    rule: "CVC 21457 - Flashing Signals",
    tip: "Flashing red acts like a stop sign with a blinking reminder.",
  },
  {
    id: "ca_004",
    stateCode: "CA",
    topic: "traffic_signs",
    difficulty: 2,
    question: "A sign says YIELD before a merge. What is the correct response?",
    options: [
      "Stop every time, even when the way is clear",
      "Speed up to match traffic and force a gap",
      "Slow or stop as needed and let conflicting traffic go first",
      "Use your horn to tell other drivers you are entering",
    ],
    correctIndex: 2,
    explanation: "A yield sign requires you to slow down or stop if needed. You must give the right-of-way to traffic close enough to be a hazard.",
    rule: "CVC 21802 - Yield Signs",
    tip: "Yield means you can move only after the conflict is gone.",
  },
  {
    id: "ca_005",
    stateCode: "CA",
    topic: "traffic_signs",
    difficulty: 2,
    question: "What does California law require when an official traffic sign gives a lawful instruction?",
    options: [
      "Obey it unless traffic is light",
      "Obey it unless your navigation app suggests another route",
      "Obey it unless directed otherwise by a police officer",
      "Obey it only if it is posted with a speed limit sign",
    ],
    correctIndex: 2,
    explanation: "Drivers must obey official traffic control devices, including regulatory signs. A police officer or authorized traffic direction can override the sign in that moment.",
    rule: "CVC 21461 - Obedience to Official Traffic Control Devices",
    tip: "Signs are rules on posts unless an officer gives a different rule.",
  },
  {
    id: "ca_006",
    stateCode: "CA",
    topic: "right_of_way",
    difficulty: 1,
    question: "Two vehicles reach an uncontrolled intersection at the same time. Which driver must yield?",
    options: [
      "The driver on the left",
      "The driver on the right",
      "The driver traveling faster",
      "The driver on the wider street",
    ],
    correctIndex: 0,
    explanation: "When vehicles enter from different highways at the same time, the driver on the left yields to the driver on the immediate right. This rule helps create an order when no signal or sign controls the intersection.",
    rule: "CVC 21800 - Intersections",
    tip: "If you see a car on your right, let the right side go right ahead.",
  },
  {
    id: "ca_007",
    stateCode: "CA",
    topic: "right_of_way",
    difficulty: 2,
    question: "When turning left across oncoming traffic, when may you begin the turn?",
    options: [
      "As soon as your signal has flashed three times",
      "Only when the turn can be made safely without interfering with approaching traffic",
      "Whenever the oncoming vehicle is more than one car length away",
      "After entering the intersection, regardless of oncoming traffic",
    ],
    correctIndex: 1,
    explanation: "A driver turning left or making a U-turn must yield to oncoming vehicles close enough to be a hazard. The turn may begin only when it is reasonably safe.",
    rule: "CVC 21801 - Left Turns and U-Turns",
    tip: "Left turns wait for a clear lane, not just a blinking signal.",
  },
  {
    id: "ca_008",
    stateCode: "CA",
    topic: "right_of_way",
    difficulty: 2,
    question: "You are entering a highway from a driveway. What must you do?",
    options: [
      "Enter slowly because driveway traffic has priority",
      "Yield to vehicles already on the highway",
      "Stop only if a stop sign is posted at the driveway",
      "Use your horn and merge immediately",
    ],
    correctIndex: 1,
    explanation: "A driver entering or crossing a highway from private property must yield to traffic already on the highway. Drivers on the roadway should not have to brake suddenly for a vehicle entering from a driveway.",
    rule: "CVC 21804 - Entry Onto Highway",
    tip: "Driveway to roadway means roadway traffic goes first.",
  },
  {
    id: "ca_009",
    stateCode: "CA",
    topic: "right_of_way",
    difficulty: 2,
    question: "What should you do when an emergency vehicle approaches with a siren and flashing red light?",
    options: [
      "Pull to the right edge and stop until it passes",
      "Keep moving at the speed limit to avoid blocking traffic",
      "Stop immediately in your lane wherever you are",
      "Move left if the right lane is occupied by parked cars",
    ],
    correctIndex: 0,
    explanation: "Drivers must yield to authorized emergency vehicles using a siren and visible red light. You should pull to the right-hand edge or curb and stop until the emergency vehicle has passed.",
    rule: "CVC 21806 - Emergency Vehicles",
    tip: "Sirens and red lights mean right side, full stop.",
  },
  {
    id: "ca_010",
    stateCode: "CA",
    topic: "right_of_way",
    difficulty: 3,
    question: "At a four-way stop, two vehicles arrive from crossing roads at the same time. Which vehicle should go first?",
    options: [
      "The vehicle that is larger",
      "The vehicle to the right",
      "The vehicle that stops farther past the limit line",
      "The vehicle with the louder horn",
    ],
    correctIndex: 1,
    explanation: "At an all-way stop, when two vehicles arrive at the same time, the driver on the left yields to the driver on the right. If arrival order is clear, the first vehicle to stop should proceed first.",
    rule: "CVC 21800 - All-Way Stop Right-of-Way",
    tip: "First stopped goes first; ties go to the right.",
  },
  {
    id: "ca_011",
    stateCode: "CA",
    topic: "speed_limits",
    difficulty: 1,
    question: "What is California's basic speed law?",
    options: [
      "You may drive the posted limit in all conditions",
      "You may exceed the limit briefly to pass safely",
      "You must never drive faster than is safe for conditions",
      "You must drive at least 10 mph below the posted limit in rain",
    ],
    correctIndex: 2,
    explanation: "California's basic speed law says you may not drive faster than is reasonable or prudent for weather, visibility, traffic, and road conditions. A posted limit is not permission to drive that speed when conditions make it unsafe.",
    rule: "CVC 22350 - Basic Speed Law",
    tip: "The safest speed is set by conditions, not just the sign.",
  },
  {
    id: "ca_012",
    stateCode: "CA",
    topic: "speed_limits",
    difficulty: 1,
    question: "Unless otherwise posted, what is the maximum speed on many California highways?",
    options: [
      "55 mph on all highways",
      "60 mph on divided highways",
      "65 mph on highways, with exceptions for posted higher limits",
      "75 mph whenever traffic is flowing quickly",
    ],
    correctIndex: 2,
    explanation: "California generally limits highway speed to 65 mph unless a higher limit is legally posted under an exception. Two-lane undivided highways are generally limited to 55 mph unless posted higher.",
    rule: "CVC 22349 - Maximum Speed Limits",
    tip: "Think 65 for highways, but 55 for two-lane undivided roads unless signs say otherwise.",
  },
  {
    id: "ca_013",
    stateCode: "CA",
    topic: "speed_limits",
    difficulty: 2,
    question: "What is the prima facie speed limit in a residential district unless signs say otherwise?",
    options: [
      "15 mph",
      "25 mph",
      "35 mph",
      "45 mph",
    ],
    correctIndex: 1,
    explanation: "California sets a 25 mph prima facie limit for business and residence districts unless otherwise posted. Prima facie means the speed is presumed lawful only when it is safe for the conditions.",
    rule: "CVC 22352 - Prima Facie Speed Limits",
    tip: "Homes and shops usually mean twenty-five unless a sign changes the line.",
  },
  {
    id: "ca_014",
    stateCode: "CA",
    topic: "speed_limits",
    difficulty: 2,
    question: "When may a California freeway have a posted 70 mph speed limit?",
    options: [
      "Only during daylight hours",
      "Only when approved and posted under state law",
      "Whenever the road has at least two lanes",
      "Only for vehicles with no passengers",
    ],
    correctIndex: 1,
    explanation: "California law allows certain highways to be posted at 70 mph when authorized. Drivers still must obey the basic speed law and slow down when conditions require it.",
    rule: "CVC 22356 - 70 MPH Speed Limits",
    tip: "Seventy is legal only when the sign and conditions both agree.",
  },
  {
    id: "ca_015",
    stateCode: "CA",
    topic: "speed_limits",
    difficulty: 2,
    question: "Is it legal to drive so slowly that you block normal traffic without a safety reason?",
    options: [
      "Yes, slower drivers always have priority",
      "Yes, as long as hazard lights are on",
      "No, unnecessary slow driving that impedes traffic is prohibited",
      "No, unless you are in the far-left lane",
    ],
    correctIndex: 2,
    explanation: "California prohibits driving so slowly that you impede or block the normal and reasonable movement of traffic. Exceptions apply when reduced speed is necessary for safe operation or required by law.",
    rule: "CVC 22400 - Minimum Speed Law",
    tip: "Too fast is dangerous, but too slow can also create danger.",
  },
  {
    id: "ca_016",
    stateCode: "CA",
    topic: "dui_laws",
    difficulty: 1,
    question: "For most adult drivers in California, what blood alcohol concentration is illegal to drive with?",
    options: [
      "0.04 percent or higher",
      "0.05 percent or higher",
      "0.08 percent or higher",
      "0.10 percent or higher",
    ],
    correctIndex: 2,
    explanation: "For most adult drivers, driving with a BAC of 0.08 percent or higher is illegal. A driver can also be guilty of DUI at a lower BAC if alcohol or drugs impair safe driving.",
    rule: "CVC 23152 - Driving Under the Influence",
    tip: "Point-oh-eight is the number, but impairment can start before it.",
  },
  {
    id: "ca_017",
    stateCode: "CA",
    topic: "dui_laws",
    difficulty: 2,
    question: "What is California's alcohol rule for drivers under 21?",
    options: [
      "They may drive below 0.08 percent BAC",
      "They may drive below 0.05 percent BAC",
      "They may drive with alcohol only if a parent is present",
      "They may not drive with 0.01 percent BAC or higher",
    ],
    correctIndex: 3,
    explanation: "California has a zero-tolerance alcohol rule for drivers under 21. A driver under 21 may not drive with a BAC of 0.01 percent or higher.",
    rule: "CVC 23136 - Zero Tolerance for Drivers Under 21",
    tip: "Under 21 means almost none: 0.01 is enough.",
  },
  {
    id: "ca_018",
    stateCode: "CA",
    topic: "dui_laws",
    difficulty: 2,
    question: "A driver under 21 has a BAC of 0.05 percent. Which statement is correct?",
    options: [
      "It is legal because the driver is below 0.08 percent",
      "It is a separate under-21 alcohol offense",
      "It is legal if the driver had food with the drink",
      "It is legal if the trip is less than one mile",
    ],
    correctIndex: 1,
    explanation: "California prohibits a driver under 21 from driving with a BAC of 0.05 percent or more. This rule is stricter than the adult 0.08 percent limit.",
    rule: "CVC 23140 - Underage Driving With BAC of 0.05 Percent or More",
    tip: "For underage drivers, 0.05 is already over the line.",
  },
  {
    id: "ca_019",
    stateCode: "CA",
    topic: "dui_laws",
    difficulty: 2,
    question: "May a driver drink from an open alcoholic beverage container while driving in California?",
    options: [
      "Yes, if the driver is not impaired",
      "Yes, if the container is covered by a paper bag",
      "No, drivers may not possess or drink from an open alcoholic beverage while driving",
      "No, but passengers may always do so in the front seat",
    ],
    correctIndex: 2,
    explanation: "California law restricts open alcoholic beverage containers in vehicles. A driver may not drink from or possess an open container while driving on a highway.",
    rule: "CVC 23223 - Open Containers in Vehicles",
    tip: "Open alcohol and open roads do not mix.",
  },
  {
    id: "ca_020",
    stateCode: "CA",
    topic: "dui_laws",
    difficulty: 3,
    question: "A driver on DUI probation in California is stopped with a BAC of 0.01 percent. What is true?",
    options: [
      "It is allowed if the driver is not impaired",
      "It can violate California's DUI probation alcohol restriction",
      "It is allowed because only 0.08 percent matters",
      "It matters only if the driver caused a crash",
    ],
    correctIndex: 1,
    explanation: "California places stricter alcohol limits on drivers who are on DUI probation. Driving with 0.01 percent BAC or higher can violate that restriction.",
    rule: "CVC 23154 - DUI Probation Alcohol Restriction",
    tip: "On DUI probation, the limit is effectively zero.",
  },
  {
    id: "ca_021",
    stateCode: "CA",
    topic: "road_markings",
    difficulty: 1,
    question: "What do double solid yellow lines generally mean on a two-way road?",
    options: [
      "Passing is allowed in both directions",
      "Passing is allowed only for the faster vehicle",
      "Do not drive to the left of the lines except for legal turns or allowed exceptions",
      "The lane is reserved for emergency vehicles",
    ],
    correctIndex: 2,
    explanation: "Double solid yellow lines separate opposing traffic and generally prohibit driving to the left of the lines. California allows limited exceptions, such as certain left turns or legal U-turns.",
    rule: "CVC 21460 - Double Parallel Lines",
    tip: "Double solid yellow is a wall, except for lawful turns through a gate.",
  },
  {
    id: "ca_022",
    stateCode: "CA",
    topic: "road_markings",
    difficulty: 2,
    question: "If a double line has one broken yellow line and one solid yellow line, who may cross to pass?",
    options: [
      "Only drivers on the side with the broken line",
      "Only drivers on the side with the solid line",
      "Drivers on either side if the road is clear",
      "No one may cross for any reason",
    ],
    correctIndex: 0,
    explanation: "When one line is broken and one is solid, passing is allowed only from the side with the broken line when safe. Drivers on the solid-line side may not cross to pass.",
    rule: "CVC 21460 - Broken and Solid Double Lines",
    tip: "Broken on your side means passing may be your side's privilege.",
  },
  {
    id: "ca_023",
    stateCode: "CA",
    topic: "road_markings",
    difficulty: 2,
    question: "What is the proper use of a two-way left-turn lane?",
    options: [
      "Use it to pass slow traffic for up to 200 feet",
      "Use it only to prepare for or complete a left turn from either direction",
      "Use it as a travel lane during heavy traffic",
      "Use it for parking if no curb space is available",
    ],
    correctIndex: 1,
    explanation: "A two-way left-turn lane is for vehicles preparing for or completing left turns from either direction. It is not a regular travel lane or passing lane.",
    rule: "CVC 21460.5 - Two-Way Left-Turn Lanes",
    tip: "Center turn lanes are for turning, not traveling.",
  },
  {
    id: "ca_024",
    stateCode: "CA",
    topic: "road_markings",
    difficulty: 2,
    question: "What does a double solid white line usually tell drivers?",
    options: [
      "Lane changes across the lines are not allowed",
      "Passing is allowed only on the right",
      "The lane ends within 500 feet",
      "The road changes from one-way to two-way traffic",
    ],
    correctIndex: 0,
    explanation: "California law generally prohibits crossing double solid white lines except where allowed by law. These lines commonly separate lanes where lane changes would be unsafe or restricted.",
    rule: "CVC 21460 - Double Solid White Lines",
    tip: "Double white means stay in sight and stay in your lane.",
  },
  {
    id: "ca_025",
    stateCode: "CA",
    topic: "road_markings",
    difficulty: 3,
    question: "When may you cross into a high-occupancy vehicle lane marked with restricted lines?",
    options: [
      "Anytime traffic in your lane is slower",
      "Only at designated openings or as permitted by law",
      "Whenever you are passing a truck",
      "Only if you use your turn signal for five seconds",
    ],
    correctIndex: 1,
    explanation: "HOV lanes often have special markings that restrict entering and exiting. You may cross those markings only at designated openings or where the law permits.",
    rule: "CVC 21655.8 - Preferential Lanes",
    tip: "For carpool lanes, enter where the lines invite you in.",
  },
  {
    id: "ca_026",
    stateCode: "CA",
    topic: "highway_driving",
    difficulty: 1,
    question: "What following distance does California law require?",
    options: [
      "Exactly one car length for every 10 mph",
      "A distance that is reasonable and prudent for speed, traffic, and road conditions",
      "At least two seconds in all weather",
      "At least 100 feet unless traffic is heavy",
    ],
    correctIndex: 1,
    explanation: "California does not set one fixed following distance for every situation. You must leave enough space based on speed, traffic, and roadway conditions.",
    rule: "CVC 21703 - Following Too Closely",
    tip: "More speed, rain, or traffic means more space.",
  },
  {
    id: "ca_027",
    stateCode: "CA",
    topic: "highway_driving",
    difficulty: 2,
    question: "Before changing lanes on a freeway, what must you do?",
    options: [
      "Signal and move if the lane looks mostly open",
      "Make sure the movement can be made with reasonable safety",
      "Slow sharply so drivers behind you can react",
      "Move first, then signal once you are halfway over",
    ],
    correctIndex: 1,
    explanation: "A driver may not turn or move right or left on a roadway until the movement can be made with reasonable safety. Signaling is required when another vehicle may be affected.",
    rule: "CVC 22107 - Turning and Lane Changes",
    tip: "Signal is the announcement; safety check is the permission.",
  },
  {
    id: "ca_028",
    stateCode: "CA",
    topic: "highway_driving",
    difficulty: 2,
    question: "What should you do when approaching a stopped emergency vehicle with flashing lights on a freeway shoulder?",
    options: [
      "Move over or slow down when safe and required",
      "Keep your lane and speed to avoid confusion",
      "Stop in your lane until waved through",
      "Move left only if traffic is completely empty",
    ],
    correctIndex: 0,
    explanation: "California's move-over law requires drivers approaching certain stopped emergency or marked vehicles to move over if safe or slow down. The goal is to protect people working near traffic.",
    rule: "CVC 21809 - Move Over or Slow Down",
    tip: "Lights on the shoulder mean give space or drop pace.",
  },
  {
    id: "ca_029",
    stateCode: "CA",
    topic: "highway_driving",
    difficulty: 2,
    question: "When driving on a roadway divided into marked lanes, what is the general lane rule?",
    options: [
      "Drive within a single lane and change lanes only when safe",
      "Straddle lanes when preparing to exit",
      "Use any part of the roadway if traffic is light",
      "Change lanes quickly to maintain the flow of traffic",
    ],
    correctIndex: 0,
    explanation: "A vehicle must be driven as nearly as practical entirely within a single lane. A lane change should not be made until it can be done safely.",
    rule: "CVC 21658 - Laned Roadways",
    tip: "One lane at a time keeps everyone predictable.",
  },
  {
    id: "ca_030",
    stateCode: "CA",
    topic: "highway_driving",
    difficulty: 3,
    question: "When passing another vehicle on a two-lane highway, what does California law generally require?",
    options: [
      "Pass on the left at a safe distance and return when safely clear",
      "Pass on either side as long as your signal is on",
      "Pass only if the other driver slows below 45 mph",
      "Pass on the shoulder if the center line is solid",
    ],
    correctIndex: 0,
    explanation: "California generally requires passing to the left at a safe distance when overtaking another vehicle. You should not return to the right side until safely clear of the vehicle being passed.",
    rule: "CVC 21750 - Overtaking and Passing",
    tip: "Pass left, clear first, return only when safe.",
  },
  {
    id: "ca_031",
    stateCode: "CA",
    topic: "parking",
    difficulty: 1,
    question: "Where is parking prohibited under California law?",
    options: [
      "On a crosswalk",
      "At the far end of a legal curb space",
      "On a residential street without painted curbs",
      "In front of your own home",
    ],
    correctIndex: 0,
    explanation: "California prohibits stopping, standing, or parking on a crosswalk except in limited circumstances for authorized passenger loading. Blocking a crosswalk creates danger for pedestrians.",
    rule: "CVC 22500 - Prohibited Stopping, Standing, or Parking",
    tip: "Crosswalks are walking space, not waiting space.",
  },
  {
    id: "ca_032",
    stateCode: "CA",
    topic: "parking",
    difficulty: 1,
    question: "How should you park on a two-way road next to a curb unless signs say otherwise?",
    options: [
      "With right wheels parallel to and within 18 inches of the curb",
      "Facing either direction if your hazard lights are on",
      "With left wheels touching the curb",
      "At a 45-degree angle whenever space is limited",
    ],
    correctIndex: 0,
    explanation: "California generally requires curb parking on a two-way roadway with the right wheels parallel to and within 18 inches of the right curb. Local signs or markings may allow other parking positions.",
    rule: "CVC 22502 - Curb Parking",
    tip: "Right side, close to the curb: eighteen inches is the memory number.",
  },
  {
    id: "ca_033",
    stateCode: "CA",
    topic: "parking",
    difficulty: 2,
    question: "How close may you park to a fire hydrant when no local rule allows otherwise?",
    options: [
      "No closer than 5 feet",
      "No closer than 10 feet",
      "No closer than 15 feet",
      "No closer than 20 feet",
    ],
    correctIndex: 2,
    explanation: "California prohibits parking within 15 feet of a fire hydrant unless a local rule or authorized direction permits it. Firefighters need immediate access without having to work around parked cars.",
    rule: "CVC 22514 - Fire Hydrants",
    tip: "Hydrant space is fifteen feet for fire access.",
  },
  {
    id: "ca_034",
    stateCode: "CA",
    topic: "parking",
    difficulty: 2,
    question: "What is true about parking in a disabled person parking space?",
    options: [
      "Anyone may park there for five minutes",
      "It is allowed if all regular spaces are full",
      "It requires proper disabled parking placard or plates",
      "It is allowed while waiting for a passenger",
    ],
    correctIndex: 2,
    explanation: "Disabled person parking spaces are reserved for vehicles displaying proper disabled parking placards or plates. Misusing the space can block access for people who legally need it.",
    rule: "CVC 22507.8 - Disabled Parking Spaces",
    tip: "Blue spaces need blue authority.",
  },
  {
    id: "ca_035",
    stateCode: "CA",
    topic: "parking",
    difficulty: 2,
    question: "May you park in front of a public or private driveway?",
    options: [
      "Yes, if you leave your phone number visible",
      "Yes, if you will be gone less than three minutes",
      "No, unless directed by a police officer or traffic control device",
      "No, unless it is your own driveway",
    ],
    correctIndex: 2,
    explanation: "California prohibits parking in front of a public or private driveway except when necessary or directed by lawful authority. Blocking a driveway prevents vehicles from safely entering or leaving the roadway.",
    rule: "CVC 22500 - Driveway Parking Restrictions",
    tip: "Driveways are doorways for cars; do not block the door.",
  },
  {
    id: "ca_036",
    stateCode: "CA",
    topic: "pedestrians",
    difficulty: 1,
    question: "What must a driver do for a pedestrian crossing in a marked crosswalk?",
    options: [
      "Yield the right-of-way and slow or stop as needed",
      "Continue if the pedestrian is on the opposite half of the road",
      "Honk before passing in front of the pedestrian",
      "Proceed if the driver has a green light regardless of the pedestrian",
    ],
    correctIndex: 0,
    explanation: "Drivers must yield to pedestrians crossing within marked crosswalks and unmarked crosswalks at intersections. Drivers must also use due care and reduce speed or take other action needed for pedestrian safety.",
    rule: "CVC 21950 - Pedestrian Right-of-Way in Crosswalks",
    tip: "Crosswalk plus pedestrian means your foot moves to the brake.",
  },
  {
    id: "ca_037",
    stateCode: "CA",
    topic: "pedestrians",
    difficulty: 2,
    question: "A vehicle ahead stops at a crosswalk. What should you assume?",
    options: [
      "The driver is parking, so you may pass slowly",
      "There may be a pedestrian crossing, so do not pass the stopped vehicle",
      "The driver is yielding only if hazard lights are on",
      "You may pass if you stay under 15 mph",
    ],
    correctIndex: 1,
    explanation: "California prohibits overtaking and passing a vehicle stopped at a crosswalk to permit a pedestrian to cross. A pedestrian may be hidden by the stopped vehicle.",
    rule: "CVC 21951 - Passing Stopped Vehicle at Crosswalk",
    tip: "A stopped car at a crosswalk may be hiding a person.",
  },
  {
    id: "ca_038",
    stateCode: "CA",
    topic: "pedestrians",
    difficulty: 2,
    question: "What is true when a pedestrian crosses outside a marked or unmarked crosswalk?",
    options: [
      "The pedestrian must yield to nearby vehicles",
      "Drivers never need to slow because the pedestrian is outside a crosswalk",
      "The pedestrian always has priority over all vehicles",
      "Drivers may speed up to clear the area",
    ],
    correctIndex: 0,
    explanation: "A pedestrian crossing outside a crosswalk must yield to vehicles close enough to be an immediate hazard. Drivers still must exercise due care to avoid collisions.",
    rule: "CVC 21954 - Crossing Outside Crosswalk",
    tip: "Outside the crosswalk, pedestrians yield, but drivers still protect.",
  },
  {
    id: "ca_039",
    stateCode: "CA",
    topic: "pedestrians",
    difficulty: 2,
    question: "Between two adjacent intersections controlled by traffic signals, where should pedestrians cross?",
    options: [
      "Only in a crosswalk",
      "Anywhere if traffic is stopped",
      "At the midpoint if the road is clear",
      "Only where there is no center divider",
    ],
    correctIndex: 0,
    explanation: "Between adjacent intersections controlled by signals or police officers, pedestrians may not cross except in a crosswalk. This rule keeps pedestrian movement predictable where traffic control is present.",
    rule: "CVC 21955 - Crossing Between Controlled Intersections",
    tip: "Signal to signal means crosswalk to crosswalk.",
  },
  {
    id: "ca_040",
    stateCode: "CA",
    topic: "pedestrians",
    difficulty: 3,
    question: "When crossing a sidewalk to enter or leave a driveway, what must a driver do?",
    options: [
      "Yield to pedestrians on the sidewalk",
      "Honk and continue because vehicles have priority",
      "Stop only if the pedestrian is in a marked crosswalk",
      "Yield only to pedestrians approaching from the driver's left",
    ],
    correctIndex: 0,
    explanation: "A driver crossing a sidewalk must yield to pedestrians and other traffic on the sidewalk. Driveways often create blind spots, so slow movement and careful looking are required.",
    rule: "CVC 21952 - Sidewalk Crossings",
    tip: "Sidewalks belong to walkers first, even across driveways.",
  },
];

const californiaBank: StateBank = {
  stateCode: "CA",
  stateName: "California",
  questions,
};

export default californiaBank;
