import type { StateBank, Topic } from "./types";

const questions: Array<{
  id: string;
  stateCode: string;
  topic: Topic;
  difficulty: 1 | 2 | 3;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  rule: string;
  tip: string;
}> = [
  { id: "fl_001", stateCode: "FL", topic: "traffic_signs", difficulty: 1, question: "What must you do at a Florida stop sign?", options: ["Slow and roll through if clear", "Stop completely at the line, crosswalk, or nearest safe point", "Stop only if cross traffic is present", "Tap the brakes and proceed"], correctIndex: 1, explanation: "A stop sign requires a complete stop before entering the intersection. Stop at the stop line, before the crosswalk, or at the nearest point with a safe view.", rule: "Florida Statutes 316.123 - Vehicle Entering Stop or Yield Intersection", tip: "Stop means wheels still before the crosswalk." },
  { id: "fl_002", stateCode: "FL", topic: "traffic_signs", difficulty: 1, question: "At a steady red light in Florida, when may you turn right?", options: ["After stopping and yielding, unless a sign prohibits it", "Without stopping if no car is coming", "Only after a green arrow", "Only from a one-way street"], correctIndex: 0, explanation: "Florida drivers must stop at a steady red signal. A right turn is allowed after stopping and yielding unless a sign prohibits the turn.", rule: "Florida Statutes 316.075 - Traffic Control Signal Devices", tip: "Red right turn starts with a full stop." },
  { id: "fl_003", stateCode: "FL", topic: "traffic_signs", difficulty: 2, question: "What does a flashing red signal mean in Florida?", options: ["Proceed with caution", "Stop, then proceed when safe", "The signal applies only to pedestrians", "Keep moving if cross traffic is stopped"], correctIndex: 1, explanation: "A flashing red signal is treated like a stop sign. After stopping, proceed only when it is safe and right-of-way rules allow it.", rule: "Florida Statutes 316.076 - Flashing Signals", tip: "Flashing red is a blinking stop sign." },
  { id: "fl_004", stateCode: "FL", topic: "traffic_signs", difficulty: 2, question: "What does a hurricane evacuation route sign indicate?", options: ["A route reserved only for emergency vehicles", "A designated road to help move traffic away from danger during evacuation", "A road with no speed limits during storms", "A route closed to local traffic"], correctIndex: 1, explanation: "Evacuation route signs identify roads used to move people away from hurricane or flood danger. Drivers should follow official directions and posted route signs during evacuation orders.", rule: "Florida Statutes 316.074 - Obedience to Traffic Control Devices", tip: "Evacuation signs are your path away from the storm." },
  { id: "fl_005", stateCode: "FL", topic: "traffic_signs", difficulty: 2, question: "What must drivers do with official Florida traffic signs and markings?", options: ["Obey them unless a navigation app disagrees", "Obey them unless directed otherwise by police or authorized traffic control", "Obey only speed signs", "Treat pavement markings as optional"], correctIndex: 1, explanation: "Drivers must obey official traffic-control devices, including signs, signals, and markings. Authorized directions can override posted devices in the moment.", rule: "Florida Statutes 316.074 - Obedience to Traffic Control Devices", tip: "Signs and markings are rules you can see." },
  { id: "fl_006", stateCode: "FL", topic: "right_of_way", difficulty: 1, question: "At an uncontrolled Florida intersection, two vehicles arrive at the same time. Who yields?", options: ["The driver on the left", "The driver on the right", "The driver on the wider road", "The driver going straight"], correctIndex: 0, explanation: "When vehicles arrive at an intersection at the same time, the driver on the left yields to the driver on the right. This rule applies when no sign or signal controls the intersection.", rule: "Florida Statutes 316.121 - Vehicles Approaching or Entering Intersections", tip: "At the same time, the right side goes first." },
  { id: "fl_007", stateCode: "FL", topic: "right_of_way", difficulty: 2, question: "When turning left in Florida, what must you do?", options: ["Yield to oncoming traffic close enough to be a hazard", "Turn first if your signal is on", "Enter halfway and force a gap", "Yield only to vehicles over 35 mph"], correctIndex: 0, explanation: "A driver turning left must yield to oncoming vehicles in the intersection or close enough to be hazardous. The turn may be made only when it can be completed safely.", rule: "Florida Statutes 316.122 - Vehicle Turning Left", tip: "Left turns wait for a clear crossing." },
  { id: "fl_008", stateCode: "FL", topic: "right_of_way", difficulty: 2, question: "You are leaving a beach parking lot and entering a road. What must you do?", options: ["Yield to roadway traffic and pedestrians crossing the driveway", "Enter first because parking lot traffic has priority", "Stop only if there is a sign", "Use your horn and proceed"], correctIndex: 0, explanation: "Drivers entering a road from a driveway or private road must yield to traffic already on the roadway. They should also watch for pedestrians and cyclists near the driveway.", rule: "Florida Statutes 316.125 - Vehicle Entering Highway From Private Road or Driveway", tip: "Parking lot to road means everyone already there goes first." },
  { id: "fl_009", stateCode: "FL", topic: "right_of_way", difficulty: 2, question: "What should you do for an emergency vehicle using siren and flashing lights?", options: ["Pull over to the closest edge and stop until it passes", "Keep moving at the speed limit", "Stop in the middle of the lane", "Speed up to clear the road"], correctIndex: 0, explanation: "Florida drivers must yield to authorized emergency vehicles using audible and visible signals. Move to the closest edge of the roadway and stop until the vehicle passes unless directed otherwise.", rule: "Florida Statutes 316.126 - Operation of Vehicles on Approach of Authorized Emergency Vehicle", tip: "Lights and siren mean edge and stop." },
  { id: "fl_010", stateCode: "FL", topic: "right_of_way", difficulty: 3, question: "At a four-way stop near a school, who should proceed first?", options: ["The first vehicle to stop; same-time arrivals yield to the right", "The largest vehicle", "The vehicle turning left", "The driver who waves first"], correctIndex: 0, explanation: "Drivers should proceed in arrival order at an all-way stop. If vehicles arrive at the same time, yield to the vehicle on the right.", rule: "Florida Statutes 316.121 and 316.123 - Intersection Right-of-Way", tip: "First stopped first; ties go right." },
  { id: "fl_011", stateCode: "FL", topic: "speed_limits", difficulty: 1, question: "What is Florida's basic speed rule?", options: ["Drive the posted limit in every condition", "Drive at a careful and prudent speed for conditions", "Always drive 10 mph below the limit in rain", "Match the fastest lane"], correctIndex: 1, explanation: "Florida requires drivers to avoid speeds greater than are reasonable and prudent under the conditions. Rain, fog, traffic, and road hazards may require slowing below the posted limit.", rule: "Florida Statutes 316.183 - Unlawful Speed", tip: "The speed sign is the max, not the weather report." },
  { id: "fl_012", stateCode: "FL", topic: "speed_limits", difficulty: 1, question: "Unless otherwise posted, what is the speed limit in a Florida municipal or residential area?", options: ["20 mph", "25 mph", "30 mph", "35 mph"], correctIndex: 2, explanation: "Florida commonly sets a 30 mph limit in municipal speed areas unless otherwise posted. Drivers must adjust speed for pedestrians, driveways, and neighborhood conditions.", rule: "Florida Statutes 316.183 - Speed Limits", tip: "Neighborhood default in Florida is often thirty unless signs say otherwise." },
  { id: "fl_013", stateCode: "FL", topic: "speed_limits", difficulty: 2, question: "On wet Florida roads after a heavy rain, what should you do?", options: ["Maintain speed because roads are flat", "Reduce speed to avoid skidding or hydroplaning", "Use cruise control to stay steady", "Drive faster to clear puddles"], correctIndex: 1, explanation: "Florida's speed law requires safe speed for conditions, and wet pavement can cause hydroplaning even on flat roads. Slowing down gives tires more time to maintain traction.", rule: "Florida Statutes 316.183 - Speed Conditions", tip: "Flat roads still get slick when water sits on top." },
  { id: "fl_014", stateCode: "FL", topic: "speed_limits", difficulty: 2, question: "What should drivers do in a posted school zone?", options: ["Obey the posted school-zone speed when active", "Use the normal road speed if no children are visible", "Slow only for crossing guards", "Stop at every school-zone sign"], correctIndex: 0, explanation: "Florida school-zone speed limits are enforceable when posted conditions are active. Children can move unpredictably, so drivers should reduce speed and stay alert.", rule: "Florida Statutes 316.1895 - School Speed Zones", tip: "When the school zone is active, the sign becomes the speed." },
  { id: "fl_015", stateCode: "FL", topic: "speed_limits", difficulty: 2, question: "Is driving too slowly illegal in Florida?", options: ["No, slow driving is always safest", "Yes, if it impedes normal and reasonable traffic without a safety reason", "Only on toll roads", "Only if hazard lights are off"], correctIndex: 1, explanation: "Florida prohibits driving so slowly as to impede or block normal and reasonable traffic. Slower driving is allowed when needed for safety or legal compliance.", rule: "Florida Statutes 316.183 - Minimum Speed", tip: "Safe speed avoids both rushing and blocking." },
  { id: "fl_016", stateCode: "FL", topic: "dui_laws", difficulty: 1, question: "For most adult drivers in Florida, what BAC is unlawful?", options: ["0.04 percent", "0.05 percent", "0.08 percent", "0.10 percent"], correctIndex: 2, explanation: "Florida prohibits driving with a blood or breath alcohol level of 0.08 or higher. A driver can also be impaired by alcohol or drugs even below that level.", rule: "Florida Statutes 316.193 - Driving Under the Influence", tip: "Point-oh-eight is the line, but impairment can arrive early." },
  { id: "fl_017", stateCode: "FL", topic: "dui_laws", difficulty: 2, question: "What is Florida's DUI rule for drugs?", options: ["Only illegal drugs count", "Driving while normal faculties are impaired by alcohol, drugs, or both is illegal", "Prescription drugs never matter", "Drugs matter only after a crash"], correctIndex: 1, explanation: "Florida DUI law covers impairment from alcoholic beverages, chemical substances, controlled substances, or combinations. A legal prescription does not excuse unsafe impaired driving.", rule: "Florida Statutes 316.193 - DUI", tip: "Legal medicine can still make illegal driving." },
  { id: "fl_018", stateCode: "FL", topic: "dui_laws", difficulty: 2, question: "What is Florida's implied consent concept?", options: ["A licensed driver has consented to lawful breath, blood, or urine testing after a DUI arrest", "A driver may refuse all tests without consequences", "Only commercial drivers consent to testing", "Testing is required only after crashes"], correctIndex: 0, explanation: "Florida's implied consent law means drivers have consented to lawful chemical testing under DUI procedures. Refusal can lead to license consequences separate from any criminal charge.", rule: "Florida Statutes 316.1932 - Implied Consent", tip: "Driving privilege comes with testing rules." },
  { id: "fl_019", stateCode: "FL", topic: "dui_laws", difficulty: 2, question: "May a driver have an open alcoholic beverage container in a vehicle on a Florida road?", options: ["Yes, if the driver is sober", "Yes, if it belongs to a passenger", "No, open containers are generally prohibited in vehicles on roads", "Only during daylight"], correctIndex: 2, explanation: "Florida generally prohibits possession of open containers of alcoholic beverages in vehicles on public roads. This rule reduces drinking while driving and related impairment risk.", rule: "Florida Statutes 316.1936 - Open Containers", tip: "Open alcohol belongs away from open roads." },
  { id: "fl_020", stateCode: "FL", topic: "dui_laws", difficulty: 3, question: "What happens to DUI seriousness when a child is in the vehicle in Florida?", options: ["Penalties can be enhanced when a minor is in the vehicle", "The BAC limit becomes 0.10 percent", "Only the passenger receives a citation", "It matters only on school property"], correctIndex: 0, explanation: "Florida law provides enhanced consequences for DUI with a minor in the vehicle. The law treats impaired driving with a child passenger as especially dangerous.", rule: "Florida Statutes 316.193 - DUI Penalties", tip: "A child passenger makes impaired driving more serious." },
  { id: "fl_021", stateCode: "FL", topic: "road_markings", difficulty: 1, question: "What does a solid yellow line on your side mean?", options: ["Passing is allowed when clear", "Do not pass from your side", "Traffic is one-way", "The lane is for buses"], correctIndex: 1, explanation: "Yellow center lines separate opposing traffic. A solid yellow line on your side generally means you may not cross it to pass.", rule: "Florida Statutes 316.074 - Traffic Control Devices", tip: "Solid yellow beside you means stay put." },
  { id: "fl_022", stateCode: "FL", topic: "road_markings", difficulty: 2, question: "What does a broken white line between lanes usually mean?", options: ["Lane changes are allowed when safe", "Lane changes are never allowed", "Opposing traffic is beside you", "Only motorcycles may cross"], correctIndex: 0, explanation: "Broken white lines separate lanes moving in the same direction. Drivers may change lanes only when the movement can be made safely.", rule: "Florida Statutes 316.089 - Driving on Roadways Laned for Traffic", tip: "Broken white means maybe, but only safely." },
  { id: "fl_023", stateCode: "FL", topic: "road_markings", difficulty: 2, question: "What must Florida drivers do on roads divided into marked lanes?", options: ["Drive as nearly as practical within a single lane", "Straddle lane lines during heavy traffic", "Ignore markings on flat roads", "Use turn lanes as passing lanes"], correctIndex: 0, explanation: "Florida requires drivers to stay as nearly as practical within a single lane. Lane changes should be made only after checking that they are safe.", rule: "Florida Statutes 316.089 - Driving on Roadways Laned for Traffic", tip: "One lane at a time keeps traffic readable." },
  { id: "fl_024", stateCode: "FL", topic: "road_markings", difficulty: 2, question: "What is a two-way left-turn lane for?", options: ["Passing slow traffic", "Preparing for left turns from either direction", "Driving during evacuation traffic", "Parking briefly"], correctIndex: 1, explanation: "A center two-way left-turn lane is for vehicles preparing to turn left from either direction. It should not be used as a regular travel lane.", rule: "Florida Statutes 316.089 - Lane Use", tip: "Center turn lanes are for turning, not cruising." },
  { id: "fl_025", stateCode: "FL", topic: "road_markings", difficulty: 3, question: "What should drivers do with lane-control arrows painted on the road?", options: ["Follow them as official lane-use instructions", "Treat them as suggestions only", "Ignore them if traffic is light", "Use any lane if signaling"], correctIndex: 0, explanation: "Official pavement markings are traffic-control devices and must be obeyed. Lane arrows tell drivers which movements are allowed from that lane.", rule: "Florida Statutes 316.074 - Obedience to Traffic Control Devices", tip: "Painted arrows choose the lane's job." },
  { id: "fl_026", stateCode: "FL", topic: "highway_driving", difficulty: 1, question: "How closely may you follow another vehicle in Florida?", options: ["As close as traffic allows", "No more closely than is reasonable and prudent", "Exactly one car length per 10 mph", "Two seconds in every condition"], correctIndex: 1, explanation: "Florida law prohibits following more closely than is reasonable and prudent. The proper gap changes with speed, traffic, and weather.", rule: "Florida Statutes 316.0895 - Following Too Closely", tip: "Rain, speed, and traffic all demand more room." },
  { id: "fl_027", stateCode: "FL", topic: "highway_driving", difficulty: 2, question: "What should you do before changing lanes on I-95 or another Florida highway?", options: ["Signal and move only when safe", "Move first and signal after", "Use the shoulder if traffic is heavy", "Force a gap by accelerating"], correctIndex: 0, explanation: "A driver should signal and make a lane change only when it can be done safely. Checking mirrors and blind spots is especially important in fast highway traffic.", rule: "Florida Statutes 316.155 and 316.089 - Signals and Lane Use", tip: "Signal announces; safety check decides." },
  { id: "fl_028", stateCode: "FL", topic: "highway_driving", difficulty: 2, question: "What is Florida's move-over law for stopped emergency, sanitation, utility, or service vehicles?", options: ["Move over when safe or slow down as required", "Move over only for ambulances", "Stop in your lane", "Maintain speed to prevent congestion"], correctIndex: 0, explanation: "Florida requires drivers to move over for certain stopped vehicles with warning lights when safe. If moving over is not possible, drivers must slow down as required by law.", rule: "Florida Statutes 316.126 - Move Over Law", tip: "Roadside lights mean lane away or speed down." },
  { id: "fl_029", stateCode: "FL", topic: "highway_driving", difficulty: 2, question: "When should headlights be on in Florida rain?", options: ["Whenever windshield wipers are in use due to rain, smoke, or fog", "Only after sunset", "Only when rain is heavy enough to flood lanes", "Only on freeways"], correctIndex: 0, explanation: "Florida requires headlights when windshield wipers are in use because of rain, smoke, or fog. Lights help others see your vehicle in low-visibility weather.", rule: "Florida Statutes 316.217 - When Lighted Lamps Are Required", tip: "Wipers on means lights on." },
  { id: "fl_030", stateCode: "FL", topic: "highway_driving", difficulty: 3, question: "During a hurricane evacuation, what should you do on designated routes?", options: ["Follow official signs, law enforcement directions, and posted traffic controls", "Drive on the shoulder whenever traffic stops", "Ignore signals because evacuation traffic has priority", "Use any closed road if your GPS suggests it"], correctIndex: 0, explanation: "Evacuation routes still operate under official traffic controls and law enforcement direction. Safe, orderly movement matters more than aggressive lane use.", rule: "Florida Statutes 316.072 and 316.074 - Obedience to Lawful Orders and Traffic Devices", tip: "In evacuation traffic, order beats urgency." },
  { id: "fl_031", stateCode: "FL", topic: "parking", difficulty: 1, question: "Where is parking prohibited in Florida?", options: ["On a crosswalk", "Beside an unpainted curb", "On your own street", "In a legal marked space"], correctIndex: 0, explanation: "Florida prohibits stopping, standing, or parking on a crosswalk. Crosswalks must remain open for pedestrians and visibility.", rule: "Florida Statutes 316.1945 - Stopping, Standing, or Parking Prohibited", tip: "Crosswalk paint is not a parking box." },
  { id: "fl_032", stateCode: "FL", topic: "parking", difficulty: 1, question: "How should you park along a two-way curb in Florida?", options: ["Facing the direction of traffic with wheels close to the curb", "Facing either direction", "At an angle unless signs prohibit it", "With left wheels to the curb"], correctIndex: 0, explanation: "Vehicles parked along a roadway should generally face the direction of lawful traffic. Parking against traffic creates risk when leaving the space.", rule: "Florida Statutes 316.195 - Additional Parking Regulations", tip: "Park with the traffic flow." },
  { id: "fl_033", stateCode: "FL", topic: "parking", difficulty: 2, question: "How close may you park to a fire hydrant in Florida?", options: ["No closer than 5 feet", "No closer than 10 feet", "No closer than 15 feet", "No closer than 20 feet"], correctIndex: 2, explanation: "Florida prohibits parking within 15 feet of a fire hydrant. Emergency crews need open access without delay.", rule: "Florida Statutes 316.1945 - Parking Near Fire Hydrant", tip: "Hydrants need fifteen feet free." },
  { id: "fl_034", stateCode: "FL", topic: "parking", difficulty: 2, question: "What is required to use a disabled parking space in Florida?", options: ["A valid disabled parking permit or plate", "A note on the dashboard", "Only a senior passenger", "Permission from a store employee"], correctIndex: 0, explanation: "Disabled parking spaces require proper permit or license plate authorization. Access aisles must also remain clear for wheelchair and mobility access.", rule: "Florida Statutes 316.1955 - Disabled Parking Enforcement", tip: "Accessible spaces require accessible parking credentials." },
  { id: "fl_035", stateCode: "FL", topic: "parking", difficulty: 2, question: "May you park in front of a driveway in Florida?", options: ["Yes, if you leave flashers on", "Yes, for quick errands", "No, blocking a driveway is prohibited", "Only in residential neighborhoods"], correctIndex: 2, explanation: "Florida prohibits parking in front of a public or private driveway. Blocking driveways interferes with safe entrance and exit.", rule: "Florida Statutes 316.1945 - Parking in Front of Driveway", tip: "Driveways are travel paths, so keep them clear." },
  { id: "fl_036", stateCode: "FL", topic: "pedestrians", difficulty: 1, question: "What must a Florida driver do for a pedestrian in a crosswalk when no signal controls traffic?", options: ["Stop and remain stopped when required for the pedestrian", "Proceed if the pedestrian is not running", "Honk and continue", "Yield only in school zones"], correctIndex: 0, explanation: "Florida requires drivers to stop and remain stopped for pedestrians in crosswalks under specified conditions. This rule is important because Florida has heavy pedestrian traffic in many communities.", rule: "Florida Statutes 316.130 - Pedestrians; Traffic Regulations", tip: "Crosswalk occupied means the car stays stopped." },
  { id: "fl_037", stateCode: "FL", topic: "pedestrians", difficulty: 2, question: "A vehicle is stopped at a crosswalk for a pedestrian. What should another driver do?", options: ["Not pass the stopped vehicle", "Pass slowly if there is room", "Pass after honking", "Pass if the pedestrian is on the far side"], correctIndex: 0, explanation: "Florida prohibits passing a vehicle stopped at a crosswalk to allow a pedestrian to cross. The stopped vehicle may hide the pedestrian.", rule: "Florida Statutes 316.130 - Passing Vehicle Stopped at Crosswalk", tip: "A stopped car at a crosswalk is a warning." },
  { id: "fl_038", stateCode: "FL", topic: "pedestrians", difficulty: 2, question: "What must pedestrians do when crossing outside a marked or unmarked crosswalk?", options: ["Yield to vehicles on the roadway", "Expect all traffic to stop", "Cross only in groups", "Cross only during daylight"], correctIndex: 0, explanation: "Pedestrians crossing outside a crosswalk must yield to vehicles. Drivers still must use due care to avoid collisions.", rule: "Florida Statutes 316.130 - Crossing Outside Crosswalk", tip: "Outside the crosswalk, pedestrians yield, but drivers stay alert." },
  { id: "fl_039", stateCode: "FL", topic: "pedestrians", difficulty: 2, question: "Why should Florida drivers be extra careful near bus stops, beaches, and tourist areas?", options: ["Pedestrian crossings and sudden stops are common", "Pedestrians never have right-of-way there", "Speed limits do not apply there", "Only buses must yield"], correctIndex: 0, explanation: "Florida roads often have heavy pedestrian activity near transit, beaches, schools, and attractions. Drivers must reduce risk by scanning ahead and yielding where required.", rule: "Florida Statutes 316.130 - Pedestrian Duties and Driver Responsibilities", tip: "Tourist areas mean eyes up and speed down." },
  { id: "fl_040", stateCode: "FL", topic: "pedestrians", difficulty: 3, question: "What duty does a Florida driver have even when a pedestrian is outside a crosswalk?", options: ["Exercise due care to avoid colliding with the pedestrian", "Maintain speed because the pedestrian must yield", "Drive around the pedestrian on the shoulder", "Stop only if police are present"], correctIndex: 0, explanation: "Florida law requires drivers to exercise due care to avoid colliding with pedestrians. Right-of-way rules do not remove the duty to prevent a crash.", rule: "Florida Statutes 316.130 - Due Care Around Pedestrians", tip: "Having priority never cancels caution." },
];

const floridaBank: StateBank = {
  stateCode: "FL",
  stateName: "Florida",
  questions,
};

export default floridaBank;
