import type { StateBank, Topic } from "./types";

const questions: Array<{
  id: string;
  stateCode: string;
  topic: Topic;
  difficulty: 1 | 2 | 3;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  rule: string;
  tip: string;
}> = [
  { id: "gen_001", stateCode: "GEN", topic: "traffic_signs", difficulty: 1, question: "What does a red octagon sign mean in every U.S. state?", options: ["Yield to cross traffic", "Stop completely before proceeding", "Road work ahead", "Do not enter"], correctIndex: 1, explanation: "A red octagon is the standard shape and color for a STOP sign across the United States. Drivers must come to a complete stop before proceeding when safe.", rule: "MUTCD - Standard STOP Sign Meaning", tip: "Eight sides means stop every time." },
  { id: "gen_002", stateCode: "GEN", topic: "traffic_signs", difficulty: 1, question: "What does a triangular red and white sign mean?", options: ["Stop completely", "Yield the right-of-way", "School crossing", "Railroad crossing"], correctIndex: 1, explanation: "An inverted triangle is the standard YIELD sign. Slow or stop as needed and let conflicting traffic or pedestrians go first.", rule: "MUTCD - Standard YIELD Sign Meaning", tip: "Triangle point down means slow down and give way." },
  { id: "gen_003", stateCode: "GEN", topic: "traffic_signs", difficulty: 2, question: "What does a flashing red traffic signal mean?", options: ["Proceed with caution", "Stop, then proceed when safe", "Only pedestrians must stop", "Traffic in your direction has priority"], correctIndex: 1, explanation: "A flashing red signal is treated like a stop sign in normal U.S. driving rules. Stop fully, then proceed only when the way is clear.", rule: "Uniform Traffic Signal Practice - Flashing Red", tip: "Flashing red is a blinking stop sign." },
  { id: "gen_004", stateCode: "GEN", topic: "traffic_signs", difficulty: 2, question: "What does a yellow diamond-shaped sign usually indicate?", options: ["A warning about road conditions or hazards ahead", "A mandatory speed limit", "A parking restriction", "A route number"], correctIndex: 0, explanation: "Yellow diamond signs are standard warning signs. They alert drivers to curves, intersections, crossings, slippery roads, or other hazards ahead.", rule: "MUTCD - Warning Sign Standards", tip: "Yellow diamond means look ahead for a hazard." },
  { id: "gen_005", stateCode: "GEN", topic: "traffic_signs", difficulty: 2, question: "What does a rectangular black-and-white sign usually communicate?", options: ["A warning only", "A regulation drivers must obey", "A scenic route", "A gas station location"], correctIndex: 1, explanation: "Black-and-white rectangular signs commonly give regulatory instructions. Speed limits, lane-use signs, and no-turn signs are examples drivers must follow.", rule: "MUTCD - Regulatory Sign Standards", tip: "Black and white means rule in sight." },
  { id: "gen_006", stateCode: "GEN", topic: "right_of_way", difficulty: 1, question: "At an uncontrolled intersection, two vehicles arrive at the same time. Who should yield?", options: ["The driver on the left", "The driver on the right", "The driver going straight", "The driver on the wider road"], correctIndex: 0, explanation: "A common right-of-way rule is that the driver on the left yields to the driver on the right when vehicles arrive at the same time. This creates a predictable order where no sign or signal controls traffic.", rule: "Standard Right-of-Way Rule - Uncontrolled Intersections", tip: "Same-time ties go to the right." },
  { id: "gen_007", stateCode: "GEN", topic: "right_of_way", difficulty: 2, question: "When turning left across oncoming traffic, what should you do?", options: ["Turn first if your signal is on", "Yield to oncoming traffic close enough to be hazardous", "Enter the intersection and make traffic stop", "Yield only to large vehicles"], correctIndex: 1, explanation: "Left-turning drivers generally must yield to oncoming vehicles close enough to create a hazard. A turn signal warns others but does not give the turning driver priority.", rule: "Standard Right-of-Way Rule - Left Turns", tip: "Left turns wait for a safe gap." },
  { id: "gen_008", stateCode: "GEN", topic: "right_of_way", difficulty: 2, question: "What should you do when an emergency vehicle approaches with flashing lights and a siren?", options: ["Pull to the right edge and stop where safe", "Keep moving at the speed limit", "Stop immediately in the left lane", "Speed up to stay ahead"], correctIndex: 0, explanation: "Drivers generally must yield to emergency vehicles using lights and sirens. Move to the right edge or curb and stop when safe until the vehicle passes.", rule: "Standard Emergency Vehicle Yield Rule", tip: "Siren and lights mean right side and stop." },
  { id: "gen_009", stateCode: "GEN", topic: "right_of_way", difficulty: 2, question: "When entering a roadway from a driveway or parking lot, what must you do?", options: ["Yield to traffic already on the road", "Enter first because you are moving slowly", "Stop only if a sign is posted", "Use your horn and proceed"], correctIndex: 0, explanation: "Drivers entering from private property generally must yield to roadway traffic. Vehicles already on the road should not need to brake suddenly for entering traffic.", rule: "Standard Entry Onto Roadway Rule", tip: "Roadway traffic goes before driveway traffic." },
  { id: "gen_010", stateCode: "GEN", topic: "right_of_way", difficulty: 3, question: "At an all-way stop, which vehicle should go first?", options: ["The first vehicle to stop; same-time arrivals yield to the right", "The largest vehicle", "The vehicle turning left", "The driver who waves first"], correctIndex: 0, explanation: "At all-way stops, drivers usually proceed in arrival order. If vehicles arrive at the same time, the driver on the left yields to the driver on the right.", rule: "Standard All-Way Stop Right-of-Way Rule", tip: "First stopped first, ties go right." },
  { id: "gen_011", stateCode: "GEN", topic: "speed_limits", difficulty: 1, question: "What does the basic speed rule require?", options: ["Drive the posted limit in all conditions", "Drive no faster than is safe for conditions", "Always drive 10 mph below the sign", "Match the fastest traffic"], correctIndex: 1, explanation: "The basic speed rule means you must drive at a safe speed for weather, visibility, traffic, and road conditions. A posted limit is not safe if conditions require slowing down.", rule: "Standard Basic Speed Rule", tip: "The sign is a ceiling, not a promise." },
  { id: "gen_012", stateCode: "GEN", topic: "speed_limits", difficulty: 1, question: "When should you reduce speed below the posted limit?", options: ["Only when police are nearby", "When rain, fog, traffic, curves, or hazards make the posted speed unsafe", "Only in school zones", "Only after sunset"], correctIndex: 1, explanation: "Drivers must reduce speed when conditions make normal speed unsafe. Weather, poor visibility, congestion, pedestrians, curves, and work zones all may require slowing.", rule: "Standard Speed Reduction for Hazards", tip: "Hazards lower the safe speed." },
  { id: "gen_013", stateCode: "GEN", topic: "speed_limits", difficulty: 2, question: "What is true about school-zone speeds?", options: ["They are optional when no crossing guard is present", "They may be lower and must be obeyed when active", "They apply only to buses", "They replace all other traffic laws"], correctIndex: 1, explanation: "School zones often have lower posted speeds during specific times or when children are present. Drivers should read the whole sign and be ready for unpredictable pedestrian movement.", rule: "Standard School-Zone Speed Practice", tip: "School signs protect children, so read the time and slow down." },
  { id: "gen_014", stateCode: "GEN", topic: "speed_limits", difficulty: 2, question: "Can driving too slowly be unsafe or illegal?", options: ["No, slower is always safer", "Yes, if it blocks normal traffic without a safety reason", "Only on interstate highways", "Only if hazard lights are off"], correctIndex: 1, explanation: "Many states prohibit driving so slowly that it impedes normal and reasonable traffic. Slower speed is allowed when needed for safety, weather, or legal compliance.", rule: "Standard Minimum Speed Principle", tip: "Safe speed is neither reckless nor blocking." },
  { id: "gen_015", stateCode: "GEN", topic: "speed_limits", difficulty: 2, question: "What should you do in a work zone?", options: ["Maintain normal speed if workers are not visible", "Obey posted work-zone speeds and watch for workers or equipment", "Use the shoulder to pass delays", "Follow closely to prevent merging"], correctIndex: 1, explanation: "Work zones can have narrowed lanes, workers, equipment, and sudden stops. Posted work-zone speeds and signs must be followed for safety.", rule: "Standard Work-Zone Speed Practice", tip: "Orange signs mean slow mind and slow speed." },
  { id: "gen_016", stateCode: "GEN", topic: "dui_laws", difficulty: 1, question: "What BAC is the common per se legal limit for most adult drivers in the United States?", options: ["0.04 percent", "0.05 percent", "0.08 percent", "0.10 percent"], correctIndex: 2, explanation: "All U.S. states use 0.08 percent BAC as the per se limit for most adult noncommercial drivers. A driver can still be impaired and unsafe below that number.", rule: "Nationwide Adult Per Se BAC Standard - 0.08", tip: "Point-oh-eight is the line, but impairment can start earlier." },
  { id: "gen_017", stateCode: "GEN", topic: "dui_laws", difficulty: 2, question: "What is the common BAC limit for commercial drivers operating commercial vehicles?", options: ["0.02 percent", "0.04 percent", "0.08 percent", "0.10 percent"], correctIndex: 1, explanation: "Commercial drivers are generally held to a stricter 0.04 percent alcohol standard while operating commercial vehicles. Commercial driving carries added responsibility because of vehicle size and passenger or cargo risk.", rule: "Federal Motor Carrier Alcohol Standard - 0.04", tip: "Commercial limit is half the usual adult limit." },
  { id: "gen_018", stateCode: "GEN", topic: "dui_laws", difficulty: 2, question: "Can prescription or over-the-counter medicine lead to impaired driving?", options: ["No, legal medicine is always safe", "Yes, if it affects alertness, judgment, or coordination", "Only if mixed with alcohol", "Only at night"], correctIndex: 1, explanation: "Legal medicine can still impair driving by causing drowsiness, slow reaction, or poor judgment. Drivers are responsible for knowing whether a medication makes driving unsafe.", rule: "Standard Impaired Driving Principle - Drugs and Medication", tip: "Legal medicine can still make illegal driving." },
  { id: "gen_019", stateCode: "GEN", topic: "dui_laws", difficulty: 2, question: "What is implied consent in driving law?", options: ["Drivers may refuse all tests without consequences", "Licensed drivers have agreed to chemical testing under lawful DUI procedures", "Only commercial drivers consent to testing", "Testing is only allowed after crashes"], correctIndex: 1, explanation: "Most states have implied-consent laws tied to the privilege of driving. Refusing a lawful chemical test can lead to license penalties separate from any DUI charge.", rule: "Standard Implied Consent Principle", tip: "Driving privilege comes with testing rules." },
  { id: "gen_020", stateCode: "GEN", topic: "dui_laws", difficulty: 3, question: "Which statement about alcohol and driving is safest and legally sound?", options: ["Coffee can make an impaired driver sober", "Only time lowers BAC meaningfully", "Cold showers remove alcohol impairment", "Driving is safe below 0.08 percent for everyone"], correctIndex: 1, explanation: "Only time allows the body to process alcohol. Coffee, showers, food, or exercise do not quickly remove impairment.", rule: "Impaired Driving Safety Standard - Alcohol Metabolism", tip: "Time is the only real sobering tool." },
  { id: "gen_021", stateCode: "GEN", topic: "road_markings", difficulty: 1, question: "What do yellow center lines separate?", options: ["Traffic moving in opposite directions", "Lanes moving in the same direction", "Parking spaces only", "Bike lanes only"], correctIndex: 0, explanation: "Yellow lines normally separate traffic moving in opposite directions. White lines normally separate traffic moving in the same direction.", rule: "MUTCD - Pavement Marking Color Standards", tip: "Yellow means opposing traffic is nearby." },
  { id: "gen_022", stateCode: "GEN", topic: "road_markings", difficulty: 1, question: "What does a solid yellow line on your side usually mean?", options: ["Passing is allowed when clear", "Do not cross to pass from your side", "Traffic is one-way", "The lane is reserved for buses"], correctIndex: 1, explanation: "A solid yellow line on your side generally means passing is not allowed from that side. Limited legal turns may still be allowed where permitted and safe.", rule: "MUTCD - No-Passing Line Markings", tip: "Solid yellow says stay on your side." },
  { id: "gen_023", stateCode: "GEN", topic: "road_markings", difficulty: 2, question: "What does a broken white line between lanes usually mean?", options: ["Lane changes are allowed when safe", "Lane changes are prohibited", "Opposing traffic is beside you", "Only motorcycles may cross"], correctIndex: 0, explanation: "Broken white lines separate lanes traveling in the same direction. You may change lanes when safe, legal, and properly signaled.", rule: "MUTCD - Lane Line Markings", tip: "Broken white means maybe, after a safety check." },
  { id: "gen_024", stateCode: "GEN", topic: "road_markings", difficulty: 2, question: "What is a two-way left-turn lane for?", options: ["Passing slow vehicles", "Preparing for left turns from either direction", "Long-distance travel", "Parking during heavy traffic"], correctIndex: 1, explanation: "A center two-way left-turn lane is used by vehicles from either direction preparing to make left turns. It is not a travel lane or passing lane.", rule: "Standard Two-Way Left-Turn Lane Practice", tip: "Center turn lanes are for turning, not traveling." },
  { id: "gen_025", stateCode: "GEN", topic: "road_markings", difficulty: 3, question: "What should you do when lane arrows are painted on the pavement?", options: ["Follow them as lane-use instructions", "Ignore them if traffic is light", "Use any lane if you signal", "Treat them as warnings only"], correctIndex: 0, explanation: "Lane-use arrows are official pavement markings that tell drivers what movements are allowed from that lane. Choose the correct lane early and follow the marked direction.", rule: "MUTCD - Lane-Use Arrow Markings", tip: "Painted arrows tell each lane its job." },
  { id: "gen_026", stateCode: "GEN", topic: "highway_driving", difficulty: 1, question: "What is a safe following-distance rule?", options: ["Follow as close as traffic allows", "Leave enough space for speed, traffic, and weather", "Use exactly one car length at all speeds", "Tailgate to prevent cut-ins"], correctIndex: 1, explanation: "Drivers should leave a reasonable and prudent following distance. Higher speeds, heavy traffic, rain, snow, or poor visibility all require more space.", rule: "Standard Following Distance Rule", tip: "Bad conditions need bigger gaps." },
  { id: "gen_027", stateCode: "GEN", topic: "highway_driving", difficulty: 2, question: "Before changing lanes on a highway, what should you do?", options: ["Signal and move only when the lane change is safe", "Move first and signal after", "Slow suddenly to create a gap", "Use the shoulder if traffic is heavy"], correctIndex: 0, explanation: "A lane change should be made only after signaling, checking mirrors and blind spots, and confirming a safe gap. A signal does not give you the right to move into another lane.", rule: "Standard Lane Change Safety Rule", tip: "Signal tells; mirrors and blind spots decide." },
  { id: "gen_028", stateCode: "GEN", topic: "highway_driving", difficulty: 2, question: "What should you do when approaching a stopped emergency or service vehicle with flashing lights on the shoulder?", options: ["Move over when safe or slow down", "Maintain speed to keep traffic flowing", "Stop in your lane", "Move over only for police cars"], correctIndex: 0, explanation: "Move-over laws exist in every state in some form. Drivers should move over when safe or slow down to protect roadside workers and emergency responders.", rule: "Nationwide Move-Over Law Principle", tip: "Roadside lights mean lane away or speed down." },
  { id: "gen_029", stateCode: "GEN", topic: "highway_driving", difficulty: 2, question: "What is the safest way to merge onto a freeway?", options: ["Stop at the end of the ramp", "Use the acceleration lane to match traffic speed and merge into a safe gap", "Force highway traffic to brake", "Merge immediately without signaling"], correctIndex: 1, explanation: "Acceleration lanes help drivers build speed before merging. Signal, check traffic, match speed when possible, and enter a safe gap.", rule: "Standard Freeway Merge Practice", tip: "Merge by matching speed, not by surprising traffic." },
  { id: "gen_030", stateCode: "GEN", topic: "highway_driving", difficulty: 3, question: "What should you do if you miss your freeway exit?", options: ["Back up on the shoulder", "Continue to the next exit", "Stop and turn around if traffic is light", "Cross the gore area quickly"], correctIndex: 1, explanation: "If you miss an exit, continue to the next safe exit. Backing up, stopping, or crossing marked gore areas on a freeway is dangerous.", rule: "Standard Freeway Exit Safety Practice", tip: "Missed exit means next exit." },
  { id: "gen_031", stateCode: "GEN", topic: "parking", difficulty: 1, question: "Where should you never park?", options: ["On a crosswalk", "In a legal marked space", "Beside an unpainted curb where allowed", "In a private driveway with permission"], correctIndex: 0, explanation: "Crosswalks must stay clear for pedestrians and visibility. Parking on a crosswalk forces pedestrians into traffic.", rule: "Standard No-Parking Location - Crosswalks", tip: "Crosswalks are walking space, not waiting space." },
  { id: "gen_032", stateCode: "GEN", topic: "parking", difficulty: 1, question: "When parallel parking on a two-way road, which direction should your vehicle face?", options: ["The same direction as traffic on your side", "Either direction if space is tight", "Opposite traffic with hazard lights on", "At an angle unless signs prohibit it"], correctIndex: 0, explanation: "Vehicles parked along a two-way road generally should face the direction of traffic. Parking against traffic makes leaving the space and seeing oncoming vehicles more dangerous.", rule: "Standard Curb Parking Practice", tip: "Park with the flow." },
  { id: "gen_033", stateCode: "GEN", topic: "parking", difficulty: 2, question: "Why must drivers avoid parking near fire hydrants?", options: ["It blocks emergency access", "It blocks GPS signals", "It damages pavement markings", "It is only a courtesy rule"], correctIndex: 0, explanation: "Fire hydrants need clear access for emergency crews. Most states set a minimum distance drivers must leave around hydrants.", rule: "Standard No-Parking Location - Fire Hydrants", tip: "Hydrants need room for hoses and crews." },
  { id: "gen_034", stateCode: "GEN", topic: "parking", difficulty: 2, question: "What is required to park in an accessible parking space?", options: ["A valid disability placard or plate", "A note on the dashboard", "Only a passenger over 65", "Permission from another driver"], correctIndex: 0, explanation: "Accessible parking spaces are reserved for vehicles with valid disability parking authorization. Access aisles next to those spaces must also remain clear.", rule: "ADA-Based Accessible Parking Practice", tip: "Accessible spaces need official credentials." },
  { id: "gen_035", stateCode: "GEN", topic: "parking", difficulty: 2, question: "Why is parking in front of a driveway unsafe?", options: ["It blocks vehicles entering or leaving the roadway", "It makes the curb look crowded", "It is safe if flashers are on", "It only matters at night"], correctIndex: 0, explanation: "Blocking a driveway can trap vehicles or force unsafe maneuvers into traffic. Most states prohibit parking in front of public or private driveways.", rule: "Standard No-Parking Location - Driveways", tip: "Driveways are doors for cars; keep them open." },
  { id: "gen_036", stateCode: "GEN", topic: "pedestrians", difficulty: 1, question: "What should drivers do for pedestrians in a crosswalk?", options: ["Yield or stop as required", "Proceed if the pedestrian is slow", "Honk and continue", "Yield only in school zones"], correctIndex: 0, explanation: "Drivers generally must yield or stop for pedestrians lawfully in crosswalks. Crosswalk safety depends on drivers slowing early and scanning both sides.", rule: "Standard Pedestrian Crosswalk Right-of-Way", tip: "Crosswalk occupied means prepare to stop." },
  { id: "gen_037", stateCode: "GEN", topic: "pedestrians", difficulty: 2, question: "A vehicle is stopped at a crosswalk. What should you assume?", options: ["It may be stopped for a hidden pedestrian", "It is parked illegally, so pass quickly", "The driver is using a phone", "It is safe to pass if you honk"], correctIndex: 0, explanation: "A stopped vehicle at a crosswalk may hide a pedestrian from your view. Passing it can put you directly into the pedestrian's path.", rule: "Standard Crosswalk Passing Safety Rule", tip: "Stopped at crosswalk means someone may be crossing." },
  { id: "gen_038", stateCode: "GEN", topic: "pedestrians", difficulty: 2, question: "What must pedestrians generally do when crossing outside a crosswalk?", options: ["Yield to vehicles on the roadway", "Expect every vehicle to stop immediately", "Cross only in groups", "Cross only during daylight"], correctIndex: 0, explanation: "Pedestrians crossing outside a crosswalk generally must yield to vehicles. Drivers still must use care to avoid hitting pedestrians.", rule: "Standard Pedestrian Crossing Outside Crosswalk Rule", tip: "Outside the crosswalk, pedestrians yield, drivers watch." },
  { id: "gen_039", stateCode: "GEN", topic: "pedestrians", difficulty: 2, question: "When turning at an intersection, what should drivers watch for?", options: ["Pedestrians and cyclists crossing in the turn path", "Only vehicles behind them", "Only traffic lights facing the cross street", "Parked cars only"], correctIndex: 0, explanation: "Turning vehicles often conflict with pedestrians and cyclists in crosswalks. Drivers must check the turn path and yield where required.", rule: "Standard Turning and Pedestrian Safety Practice", tip: "Before turning, look where the car will go." },
  { id: "gen_040", stateCode: "GEN", topic: "pedestrians", difficulty: 3, question: "What duty does a driver have even when a pedestrian makes a mistake?", options: ["Exercise due care to avoid a collision", "Maintain speed because the driver has priority", "Use the horn and continue", "Pass as close as possible"], correctIndex: 0, explanation: "Right-of-way rules do not remove a driver's duty to avoid crashes. Drivers should slow, steer safely, and stay alert when pedestrians are nearby.", rule: "Standard Driver Due Care Principle", tip: "Having priority never cancels caution." },
];

const genericBank: StateBank = {
  stateCode: "GEN",
  stateName: "Generic DMV",
  questions,
};

export default genericBank;
