import type { StateBank, Topic } from "./types";

const questions: Array<{
  id: string;
  stateCode: string;
  topic: Topic;
  difficulty: 1 | 2 | 3;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  rule: string;
  tip: string;
}> = [
  { id: "il_001", stateCode: "IL", topic: "traffic_signs", difficulty: 1, question: "What must you do at an Illinois stop sign?", options: ["Slow and continue if clear", "Stop completely at the line, crosswalk, or nearest safe point", "Stop only when cross traffic is present", "Roll through after signaling"], correctIndex: 1, explanation: "A stop sign requires a complete stop at the marked stop line, before the crosswalk, or before entering the intersection. You may proceed only when safe and lawful.", rule: "625 ILCS 5/11-1204 - Stop and Yield Signs", tip: "Stop signs require stopped wheels." },
  { id: "il_002", stateCode: "IL", topic: "traffic_signs", difficulty: 1, question: "At a steady red signal in Illinois, what must a driver do before turning right where allowed?", options: ["Stop first, then yield to pedestrians and traffic", "Turn without stopping if clear", "Wait for a green arrow in every case", "Turn only after honking"], correctIndex: 0, explanation: "Illinois requires drivers facing a steady red signal to stop. A right turn after stopping may be allowed unless prohibited, but the driver must yield first.", rule: "625 ILCS 5/11-306 - Traffic-Control Signal Legend", tip: "Red turn begins with a stop." },
  { id: "il_003", stateCode: "IL", topic: "traffic_signs", difficulty: 2, question: "What does a flashing red light mean in Illinois?", options: ["Proceed carefully without stopping", "Stop, then proceed when safe", "The light applies only to pedestrians", "Traffic in your direction has priority"], correctIndex: 1, explanation: "A flashing red signal requires a stop like a stop sign. After stopping, proceed only when it is safe and right-of-way rules allow.", rule: "625 ILCS 5/11-306 - Flashing Signals", tip: "Flashing red is a stop sign with electricity." },
  { id: "il_004", stateCode: "IL", topic: "traffic_signs", difficulty: 2, question: "At a yield sign on a Chicago ramp or neighborhood street, what must you do?", options: ["Stop every time", "Slow or stop as needed and yield to hazardous traffic", "Accelerate to match traffic immediately", "Enter first if you are already signaling"], correctIndex: 1, explanation: "A yield sign requires a driver to slow down and stop if needed. The driver must yield to vehicles close enough to be an immediate hazard.", rule: "625 ILCS 5/11-1204 - Stop and Yield Signs", tip: "Yield means wait for a real opening." },
  { id: "il_005", stateCode: "IL", topic: "traffic_signs", difficulty: 2, question: "What must Illinois drivers do with official traffic signs and markings?", options: ["Obey them unless traffic is light", "Obey them unless directed otherwise by a police officer", "Obey only posted speed signs", "Treat pavement markings as advice"], correctIndex: 1, explanation: "Illinois drivers must obey official traffic-control devices. Lawful directions from police or authorized traffic control can override signs or signals.", rule: "625 ILCS 5/11-305 - Obedience to Traffic-Control Devices", tip: "Signs, signals, and paint all speak traffic law." },
  { id: "il_006", stateCode: "IL", topic: "right_of_way", difficulty: 1, question: "Two drivers reach an uncontrolled Illinois intersection at the same time. Who yields?", options: ["The driver on the left", "The driver on the right", "The driver going straight", "The driver on the wider road"], correctIndex: 0, explanation: "When vehicles arrive at about the same time, the driver on the left yields to the driver on the right. This rule applies when no sign or signal controls the intersection.", rule: "625 ILCS 5/11-901 - Vehicles Approaching or Entering Intersection", tip: "Same-time intersections favor the right." },
  { id: "il_007", stateCode: "IL", topic: "right_of_way", difficulty: 2, question: "When turning left in Illinois, what must you do?", options: ["Yield to oncoming traffic close enough to be a hazard", "Turn first if your signal is on", "Enter the lane and make traffic stop", "Yield only to emergency vehicles"], correctIndex: 0, explanation: "A driver intending to turn left must yield to oncoming traffic that is in the intersection or close enough to be a hazard. The turn should be made only when it can be completed safely.", rule: "625 ILCS 5/11-902 - Vehicle Turning Left", tip: "Left turns wait for oncoming lanes to clear." },
  { id: "il_008", stateCode: "IL", topic: "right_of_way", difficulty: 2, question: "You are entering a road from an alley or driveway in Illinois. What must you do?", options: ["Yield to traffic on the roadway and pedestrians on the sidewalk", "Enter slowly because alley traffic has priority", "Stop only if posted", "Honk and continue"], correctIndex: 0, explanation: "Drivers entering from an alley, building, private road, or driveway must yield to traffic on the roadway. They must also be alert for pedestrians crossing the driveway area.", rule: "625 ILCS 5/11-905 - Vehicle Entering Roadway", tip: "From alley to street, yield before you meet." },
  { id: "il_009", stateCode: "IL", topic: "right_of_way", difficulty: 2, question: "What must you do when an emergency vehicle approaches with lights and siren?", options: ["Pull to the right edge and stop until it passes", "Keep driving if traffic is heavy", "Stop in the left lane", "Speed up to clear the block"], correctIndex: 0, explanation: "Illinois drivers must yield to authorized emergency vehicles using audible and visual signals. Pull to the right-hand edge or curb and stop until the vehicle passes unless directed otherwise.", rule: "625 ILCS 5/11-907 - Operation of Vehicles on Approach of Authorized Emergency Vehicles", tip: "Siren means right and stopped." },
  { id: "il_010", stateCode: "IL", topic: "right_of_way", difficulty: 3, question: "At an all-way stop in Illinois, what is the correct order?", options: ["First stopped first; same-time arrivals yield to the right", "Largest vehicle first", "Left-turning vehicle first", "Driver who flashes headlights first"], correctIndex: 0, explanation: "At all-way stops, vehicles generally proceed in arrival order. When vehicles arrive at the same time, the driver on the left yields to the driver on the right.", rule: "625 ILCS 5/11-901 and 11-1204 - Intersection and Stop Sign Rules", tip: "Arrival order first, right-side tie breaker second." },
  { id: "il_011", stateCode: "IL", topic: "speed_limits", difficulty: 1, question: "What is Illinois's basic speed rule?", options: ["Drive the posted limit in all conditions", "Drive at a speed reasonable and proper for traffic and conditions", "Always drive 10 mph under the limit in snow", "Match the fastest lane"], correctIndex: 1, explanation: "Illinois requires drivers to use a speed that is reasonable and proper for conditions. Snow, ice, fog, traffic, and road work can require speeds below the posted limit.", rule: "625 ILCS 5/11-601 - General Speed Restrictions", tip: "Posted speed is not permission to ignore winter." },
  { id: "il_012", stateCode: "IL", topic: "speed_limits", difficulty: 1, question: "Unless posted otherwise, what is a common Illinois urban district speed limit?", options: ["20 mph", "25 mph", "30 mph", "35 mph"], correctIndex: 2, explanation: "Illinois commonly sets a 30 mph limit in urban districts unless otherwise posted. Drivers must still reduce speed where conditions require.", rule: "625 ILCS 5/11-601 - Speed Restrictions", tip: "City default is commonly thirty, but signs can change it." },
  { id: "il_013", stateCode: "IL", topic: "speed_limits", difficulty: 2, question: "What should you do on icy Illinois roads?", options: ["Keep the posted speed if traffic is moving", "Reduce speed and increase following distance", "Use cruise control for steady traction", "Brake hard before every curve"], correctIndex: 1, explanation: "Illinois's basic speed rule requires slowing for dangerous road conditions. Ice greatly reduces traction, so drivers need lower speeds and larger gaps.", rule: "625 ILCS 5/11-601 - Speed Reasonable for Conditions", tip: "Ice steals grip, so give yourself time." },
  { id: "il_014", stateCode: "IL", topic: "speed_limits", difficulty: 2, question: "What is required in a posted Illinois school zone?", options: ["Obey the posted school-zone limit when children are present or the signs apply", "Use the normal speed if no police are visible", "Slow only for buses", "Stop at every school sign"], correctIndex: 0, explanation: "Illinois school-zone speed restrictions apply under posted conditions, commonly when children are present. Drivers should slow and scan carefully around schools.", rule: "625 ILCS 5/11-605 - Special Speed Limit While Passing Schools", tip: "School zones are built around children, not traffic flow." },
  { id: "il_015", stateCode: "IL", topic: "speed_limits", difficulty: 2, question: "Is driving too slowly illegal in Illinois?", options: ["No, slower is always safer", "Yes, if it impedes normal and reasonable traffic without cause", "Only on tollways", "Only if hazard lights are off"], correctIndex: 1, explanation: "Illinois prohibits driving so slowly as to impede normal and reasonable movement of traffic. Slower speed is allowed when necessary for safety or legal compliance.", rule: "625 ILCS 5/11-606 - Minimum Speed Regulation", tip: "Do not speed, but do not become a rolling roadblock." },
  { id: "il_016", stateCode: "IL", topic: "dui_laws", difficulty: 1, question: "For most adult drivers in Illinois, what BAC is illegal?", options: ["0.04 percent", "0.05 percent", "0.08 percent", "0.10 percent"], correctIndex: 2, explanation: "Illinois prohibits driving with an alcohol concentration of 0.08 or more. A driver can also violate DUI law when alcohol or drugs impair safe driving.", rule: "625 ILCS 5/11-501 - Driving Under the Influence", tip: "Point-oh-eight is the legal line, but impairment can start before it." },
  { id: "il_017", stateCode: "IL", topic: "dui_laws", difficulty: 2, question: "What is Illinois's DUI rule for drugs?", options: ["Only illegal drugs count", "Driving impaired by drugs, alcohol, or a combination is illegal", "Prescription drugs never matter", "Drugs matter only after crashes"], correctIndex: 1, explanation: "Illinois DUI law covers impairment from alcohol, drugs, intoxicating compounds, or combinations. A prescription does not permit driving while impaired.", rule: "625 ILCS 5/11-501 - DUI", tip: "Legal medicine can still cause illegal impairment." },
  { id: "il_018", stateCode: "IL", topic: "dui_laws", difficulty: 2, question: "What does Illinois implied consent mean?", options: ["Drivers are deemed to consent to chemical testing under DUI arrest procedures", "Drivers may refuse tests without consequences", "Only CDL drivers consent to tests", "Testing happens only after crashes"], correctIndex: 0, explanation: "Illinois implied consent law ties driving privileges to chemical testing after a qualifying DUI arrest. Refusal can trigger license consequences.", rule: "625 ILCS 5/11-501.1 - Implied Consent", tip: "Driving privilege comes with testing responsibility." },
  { id: "il_019", stateCode: "IL", topic: "dui_laws", difficulty: 2, question: "May an Illinois driver have an open alcohol container in the passenger area?", options: ["Yes, if sober", "Yes, if it belongs to a passenger", "No, open alcohol in the passenger area is generally prohibited", "Only on private tollways"], correctIndex: 2, explanation: "Illinois generally prohibits transporting, carrying, or possessing open alcoholic liquor in the passenger area of a motor vehicle on a highway. This rule applies separately from DUI impairment.", rule: "625 ILCS 5/11-502 - Transportation or Possession of Alcoholic Liquor in Motor Vehicle", tip: "Open alcohol and passenger seats do not belong together." },
  { id: "il_020", stateCode: "IL", topic: "dui_laws", difficulty: 3, question: "What is Illinois's zero-tolerance concept for drivers under 21?", options: ["Drivers under 21 may face consequences for any trace of alcohol", "Drivers under 21 may drive below 0.08", "Only school-zone driving matters", "Alcohol matters only after a crash"], correctIndex: 0, explanation: "Illinois has zero-tolerance rules for drivers under 21 with alcohol in their system. The standard is stricter than the adult 0.08 DUI threshold.", rule: "625 ILCS 5/11-501.8 - Zero Tolerance", tip: "Under 21 means alcohol and driving do not mix." },
  { id: "il_021", stateCode: "IL", topic: "road_markings", difficulty: 1, question: "What does a solid yellow line on your side mean?", options: ["Passing is allowed when clear", "Do not cross to pass from your side", "Traffic is one-way", "Only trucks may cross"], correctIndex: 1, explanation: "Yellow lines separate opposing traffic, and a solid yellow line on your side generally means no passing. Cross only when a lawful movement is allowed and safe.", rule: "625 ILCS 5/11-305 - Traffic-Control Devices", tip: "Solid yellow means stay on your side." },
  { id: "il_022", stateCode: "IL", topic: "road_markings", difficulty: 2, question: "What does a broken white line usually permit?", options: ["A lane change when safe", "No lane changes", "Passing into opposing traffic", "Parking in the lane"], correctIndex: 0, explanation: "Broken white lines separate lanes moving in the same direction. They generally permit lane changes when safe and legal.", rule: "625 ILCS 5/11-709 - Driving on Roadways Laned for Traffic", tip: "Broken white is permission only after a safety check." },
  { id: "il_023", stateCode: "IL", topic: "road_markings", difficulty: 2, question: "What must drivers do on a roadway marked for lanes?", options: ["Drive as nearly as practical within one lane", "Use two lanes on snowy roads", "Ignore lane lines during rush hour", "Change lanes without signaling"], correctIndex: 0, explanation: "Illinois requires a vehicle to be driven as nearly as practical within a single lane. A lane change must not be made until it can be done safely.", rule: "625 ILCS 5/11-709 - Lane Usage", tip: "Stay predictable by staying in your lane." },
  { id: "il_024", stateCode: "IL", topic: "road_markings", difficulty: 2, question: "What are reversible lane signals or markings in Chicago-area traffic used for?", options: ["Changing lane direction or allowed use based on traffic control", "Letting drivers choose either direction", "Marking lanes where speed limits do not apply", "Creating parking lanes during rush hour"], correctIndex: 0, explanation: "Lane-use control signs and signals can assign lanes for different directions or uses at different times. Drivers must obey the displayed signal or marking.", rule: "625 ILCS 5/11-305 and 11-306 - Traffic-Control Devices and Signals", tip: "Lane signals tell you what the lane is today." },
  { id: "il_025", stateCode: "IL", topic: "road_markings", difficulty: 3, question: "What should you do with tollway lane arrows and I-PASS/open-road tolling markings?", options: ["Follow posted lane-control signs and markings", "Ignore them if your transponder works", "Change lanes at the last second", "Stop in any lane to pay"], correctIndex: 0, explanation: "Tollway signs and lane markings are traffic-control devices and must be followed. Last-second lane changes around toll plazas or open-road tolling areas create crash risk.", rule: "625 ILCS 5/11-305 - Obedience to Traffic-Control Devices", tip: "Choose toll lanes early and follow the markings." },
  { id: "il_026", stateCode: "IL", topic: "highway_driving", difficulty: 1, question: "How close may you follow another vehicle in Illinois?", options: ["As close as needed to prevent merges", "No more closely than is reasonable and prudent", "One car length in all conditions", "Two seconds only in summer"], correctIndex: 1, explanation: "Illinois prohibits following more closely than is reasonable and prudent. Speed, traffic, weather, and road surface all affect safe spacing.", rule: "625 ILCS 5/11-710 - Following Too Closely", tip: "Bad weather turns small gaps into big risks." },
  { id: "il_027", stateCode: "IL", topic: "highway_driving", difficulty: 2, question: "Before changing lanes on an Illinois tollway, what should you do?", options: ["Signal and move only when safe", "Move first and signal after", "Use the shoulder to pass congestion", "Force a gap by accelerating"], correctIndex: 0, explanation: "Drivers must use signals and may change lanes only when the movement can be made safely. Tollway speeds make blind-spot checks especially important.", rule: "625 ILCS 5/11-804 and 11-709 - Signals and Lane Use", tip: "Signal, check, then change." },
  { id: "il_028", stateCode: "IL", topic: "highway_driving", difficulty: 2, question: "What is Scott's Law in Illinois?", options: ["Move over and slow down for stopped emergency or authorized vehicles with lights", "Stop in your lane for every tow truck", "Move over only for police vehicles", "Maintain speed to avoid traffic backups"], correctIndex: 0, explanation: "Scott's Law requires drivers approaching certain stopped vehicles with flashing lights to change lanes if safe and reduce speed. It protects emergency responders and roadside workers.", rule: "625 ILCS 5/11-907 - Scott's Law", tip: "Flashing lights roadside mean move over and slow down." },
  { id: "il_029", stateCode: "IL", topic: "highway_driving", difficulty: 2, question: "When must headlights be used in Illinois?", options: ["Only after midnight", "From sunset to sunrise and when weather requires wipers or visibility is poor", "Only on interstates", "Only when high beams are needed"], correctIndex: 1, explanation: "Illinois requires headlights during nighttime and during certain poor-visibility weather conditions, including when windshield wipers are needed. Lights make your vehicle visible in snow, rain, and fog.", rule: "625 ILCS 5/12-201 - When Lighted Lamps Are Required", tip: "Wipers on or visibility down means lights on." },
  { id: "il_030", stateCode: "IL", topic: "highway_driving", difficulty: 3, question: "What should you remember when passing snowplows in Illinois winter driving?", options: ["Give extra room and pass only when safe and legal", "Pass quickly on the shoulder", "Follow closely to use the cleared path", "Drive between multiple plows"], correctIndex: 0, explanation: "Snowplows may create snow clouds, wide blade paths, and changing road conditions. Passing should be avoided unless it can be done safely and legally with plenty of space.", rule: "625 ILCS 5/11-601 and 11-703 - Safe Speed and Passing", tip: "Plows clear the road; do not crowd their work zone." },
  { id: "il_031", stateCode: "IL", topic: "parking", difficulty: 1, question: "Where is parking prohibited in Illinois?", options: ["On a crosswalk", "Beside an unpainted curb", "In a marked legal space", "In front of your house"], correctIndex: 0, explanation: "Illinois prohibits stopping, standing, or parking on a crosswalk. Pedestrians need the crossing area open and visible.", rule: "625 ILCS 5/11-1303 - Stopping, Standing or Parking Prohibited", tip: "Crosswalks are for people, not parked cars." },
  { id: "il_032", stateCode: "IL", topic: "parking", difficulty: 1, question: "How should you park parallel on a two-way Illinois street?", options: ["Facing the direction of traffic with wheels close to the curb", "Facing either direction", "At an angle unless signs prohibit it", "With left wheels against the curb"], correctIndex: 0, explanation: "Vehicles parked on a two-way roadway should face the direction of authorized traffic. Parking against traffic makes reentry unsafe.", rule: "625 ILCS 5/11-1304 - Additional Parking Regulations", tip: "Park with traffic, not against it." },
  { id: "il_033", stateCode: "IL", topic: "parking", difficulty: 2, question: "How close may you park to a fire hydrant in Illinois?", options: ["No closer than 5 feet", "No closer than 10 feet", "No closer than 15 feet", "No closer than 20 feet"], correctIndex: 2, explanation: "Illinois prohibits parking within 15 feet of a fire hydrant. Emergency access must stay clear.", rule: "625 ILCS 5/11-1303 - Parking Near Fire Hydrant", tip: "Hydrant equals fifteen feet clear." },
  { id: "il_034", stateCode: "IL", topic: "parking", difficulty: 2, question: "What is required to park in an accessible parking space in Illinois?", options: ["A valid disability plate or placard", "A note on the dashboard", "A passenger over 65", "Permission from a store"], correctIndex: 0, explanation: "Accessible parking spaces require valid disability plates or placards. Access aisles must also remain clear for mobility access.", rule: "625 ILCS 5/11-1301.3 - Unauthorized Use of Parking Places Reserved for Persons With Disabilities", tip: "Accessible parking needs proper credentials." },
  { id: "il_035", stateCode: "IL", topic: "parking", difficulty: 2, question: "May you park in front of a driveway in Illinois?", options: ["Yes, if flashers are on", "Yes, for brief loading", "No, blocking a driveway is prohibited", "Only in winter"], correctIndex: 2, explanation: "Illinois prohibits parking in front of a public or private driveway. Blocking driveways can trap vehicles and create unsafe maneuvers.", rule: "625 ILCS 5/11-1303 - Parking in Front of Driveway", tip: "Driveways need clear in-and-out space." },
  { id: "il_036", stateCode: "IL", topic: "pedestrians", difficulty: 1, question: "At an Illinois crosswalk without active signals, what must a driver do for a pedestrian?", options: ["Stop and yield when the pedestrian is on the driver's half or close enough to be in danger", "Proceed if the pedestrian is walking slowly", "Honk and continue", "Yield only at marked crosswalks"], correctIndex: 0, explanation: "Illinois requires drivers to stop and yield to pedestrians in crosswalks under specified conditions. This includes when the pedestrian is on the driver's half or approaching so closely as to be in danger.", rule: "625 ILCS 5/11-1002 - Pedestrians' Right-of-Way at Crosswalks", tip: "If the walker is in or near your path, stop." },
  { id: "il_037", stateCode: "IL", topic: "pedestrians", difficulty: 2, question: "A vehicle has stopped at a crosswalk for a pedestrian. What should another driver do?", options: ["Not pass the stopped vehicle", "Pass slowly if there is room", "Pass after honking", "Pass if the pedestrian is more than one lane away"], correctIndex: 0, explanation: "Passing a vehicle stopped for a pedestrian at a crosswalk is dangerous because the pedestrian may be hidden. Illinois pedestrian rules require drivers to protect crosswalk users.", rule: "625 ILCS 5/11-1002 - Crosswalk Right-of-Way", tip: "Stopped at crosswalk means assume someone is crossing." },
  { id: "il_038", stateCode: "IL", topic: "pedestrians", difficulty: 2, question: "What must pedestrians do when crossing outside a crosswalk in Illinois?", options: ["Yield to vehicles on the roadway", "Expect all drivers to stop", "Cross only in groups", "Cross only during daylight"], correctIndex: 0, explanation: "Pedestrians crossing outside a marked or unmarked crosswalk must yield to vehicles. Drivers still must use care to avoid collisions.", rule: "625 ILCS 5/11-1003 - Crossing at Other Than Crosswalks", tip: "Outside crosswalks, pedestrians yield, drivers watch." },
  { id: "il_039", stateCode: "IL", topic: "pedestrians", difficulty: 2, question: "Why should drivers be extra alert in Chicago near transit stops and intersections?", options: ["Pedestrians and cyclists may enter crosswalks frequently", "Vehicles always have priority on green", "Crosswalk laws do not apply downtown", "Only taxis must yield"], correctIndex: 0, explanation: "Dense city areas create frequent pedestrian crossings, bus stops, cyclists, and turning conflicts. Drivers must yield where required and slow enough to react.", rule: "625 ILCS 5/11-1002 and 11-1003.1 - Pedestrian Safety", tip: "City driving needs scanning, not guessing." },
  { id: "il_040", stateCode: "IL", topic: "pedestrians", difficulty: 3, question: "What duty does an Illinois driver have even when a pedestrian is outside a crosswalk?", options: ["Exercise due care to avoid colliding with the pedestrian", "Maintain speed because the pedestrian must yield", "Use the horn and continue", "Pass on either side"], correctIndex: 0, explanation: "Illinois requires drivers to exercise due care to avoid colliding with pedestrians. Right-of-way rules do not remove the duty to prevent a crash.", rule: "625 ILCS 5/11-1003.1 - Drivers to Exercise Due Care", tip: "Right-of-way never replaces caution." },
];

const illinoisBank: StateBank = {
  stateCode: "IL",
  stateName: "Illinois",
  questions,
};

export default illinoisBank;
