import type { StateBank, Topic } from "./types";

const questions: Array<{
  id: string;
  stateCode: string;
  topic: Topic;
  difficulty: 1 | 2 | 3;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  rule: string;
  tip: string;
}> = [
  { id: "ny_001", stateCode: "NY", topic: "traffic_signs", difficulty: 1, question: "What must you do at a New York stop sign?", options: ["Slow down and continue if the way looks clear", "Stop completely at the line, crosswalk, or safe viewing point", "Stop only when another vehicle is present", "Roll forward until cross traffic reacts"], correctIndex: 1, explanation: "A stop sign requires a complete stop at the marked stop line, crosswalk, or nearest point with a view of traffic. You may proceed only when the right-of-way rules allow it.", rule: "VTL 1172 - Stop Signs and Yield Signs", tip: "In New York, stop means full stop before the crosswalk." },
  { id: "ny_002", stateCode: "NY", topic: "traffic_signs", difficulty: 2, question: "In New York City, when may a driver turn right on red?", options: ["After stopping, unless a sign says no turn", "Only when a sign specifically permits it", "Whenever no pedestrians are in the crosswalk", "Only from a one-way street"], correctIndex: 1, explanation: "New York City generally prohibits right turns on red unless a sign allows the turn. Outside NYC, right on red may be allowed after stopping unless prohibited by signs.", rule: "VTL 1111 - Traffic-Control Signal Indications; NYC Traffic Rules", tip: "NYC flips the usual rule: no right on red unless the sign invites it." },
  { id: "ny_003", stateCode: "NY", topic: "traffic_signs", difficulty: 1, question: "What does a steady yellow light mean in New York?", options: ["Speed up to clear the intersection", "The signal is changing to red, so stop if you can do so safely", "Traffic in all directions must stop", "Pedestrians have priority but vehicles may continue"], correctIndex: 1, explanation: "A steady yellow signal warns that the related green movement is ending and red will follow. Drivers should stop if they can do so safely before entering the intersection.", rule: "VTL 1111 - Traffic-Control Signal Indications", tip: "Yellow is a warning to prepare to stop, not an invitation to race." },
  { id: "ny_004", stateCode: "NY", topic: "traffic_signs", difficulty: 2, question: "At a yield sign in New York, what is required?", options: ["Stop every time no matter what", "Slow or stop as needed and yield to traffic close enough to be hazardous", "Enter first if your vehicle is on the main road", "Honk and merge carefully"], correctIndex: 1, explanation: "A yield sign requires a driver to slow and stop if necessary for safety. The driver must yield to vehicles close enough to create an immediate hazard.", rule: "VTL 1172 - Stop Signs and Yield Signs", tip: "Yield means the gap has to be real, not hopeful." },
  { id: "ny_005", stateCode: "NY", topic: "traffic_signs", difficulty: 2, question: "What must drivers do with official traffic-control signs and markings?", options: ["Obey them unless traffic is light", "Obey them unless directed otherwise by a police officer", "Obey them only on state highways", "Obey signs but not pavement markings"], correctIndex: 1, explanation: "Drivers must obey official traffic-control devices such as signs, signals, and markings. A lawful direction from a police officer can override the posted device.", rule: "VTL 1110 - Obedience to Traffic-Control Devices", tip: "Signs are commands until an officer gives a different command." },
  { id: "ny_006", stateCode: "NY", topic: "right_of_way", difficulty: 1, question: "At an uncontrolled intersection, two vehicles arrive at about the same time. Who yields?", options: ["The driver on the left", "The driver on the right", "The driver going faster", "The driver on the narrower road"], correctIndex: 0, explanation: "When vehicles approach an intersection at about the same time, the driver on the left yields to the driver on the right. This creates a predictable order when no signal or sign controls traffic.", rule: "VTL 1140 - Vehicle Approaching or Entering Intersection", tip: "Same-time tie goes to the car on the right." },
  { id: "ny_007", stateCode: "NY", topic: "right_of_way", difficulty: 2, question: "When turning left in New York, what must you do with oncoming traffic?", options: ["Turn first if your signal is on", "Yield to oncoming vehicles close enough to be a hazard", "Enter the intersection and wait for traffic to stop", "Yield only to buses and trucks"], correctIndex: 1, explanation: "A driver turning left must yield to oncoming vehicles that are in the intersection or close enough to be an immediate hazard. A turn signal does not give the turning vehicle priority.", rule: "VTL 1141 - Vehicle Turning Left", tip: "Left turns borrow space only after oncoming traffic clears." },
  { id: "ny_008", stateCode: "NY", topic: "right_of_way", difficulty: 2, question: "What should you do for an emergency vehicle approaching with siren and flashing lights?", options: ["Pull to the right edge and stop until it passes", "Keep moving if you are in heavy city traffic", "Stop in the lane immediately", "Speed up to avoid delaying it"], correctIndex: 0, explanation: "New York drivers must yield to emergency vehicles using audible and visible signals. Pull to the right edge or curb and stop until the vehicle passes unless directed otherwise.", rule: "VTL 1144 - Operation of Vehicles on Approach of Authorized Emergency Vehicles", tip: "Siren behind you means right side, full stop." },
  { id: "ny_009", stateCode: "NY", topic: "right_of_way", difficulty: 2, question: "You are entering a road from a driveway in New York. What must you do?", options: ["Yield to traffic on the roadway and pedestrians on the sidewalk", "Enter slowly because exiting traffic has priority", "Stop only if there is a posted sign", "Use your horn before crossing the sidewalk"], correctIndex: 0, explanation: "Drivers entering from a driveway must yield to traffic already on the roadway. They must also watch for and yield to pedestrians when crossing a sidewalk area.", rule: "VTL 1143 - Vehicle Entering Roadway", tip: "Driveways meet two paths: sidewalk first, roadway next." },
  { id: "ny_010", stateCode: "NY", topic: "right_of_way", difficulty: 3, question: "At a busy all-way stop in New York, what order should drivers follow?", options: ["Largest vehicle first", "First arrival first; same-time arrivals yield to the right", "Left-turning vehicles first", "Whoever waves first must go first"], correctIndex: 1, explanation: "At all-way stops, drivers should proceed in order of arrival. If vehicles arrive at the same time, the driver on the left yields to the driver on the right.", rule: "VTL 1140 and 1172 - Intersection and Stop Sign Rules", tip: "First stopped goes first; ties go right." },
  { id: "ny_011", stateCode: "NY", topic: "speed_limits", difficulty: 1, question: "What is New York's basic speed rule?", options: ["Drive the posted speed in all conditions", "Drive at a speed that is reasonable and prudent under the conditions", "Drive 10 mph below the limit in rain", "Match the speed of surrounding traffic"], correctIndex: 1, explanation: "New York requires drivers to use reasonable and prudent speed for actual and potential hazards. A posted limit is not safe if weather, traffic, visibility, or road conditions require slower driving.", rule: "VTL 1180 - Basic Rule and Maximum Limits", tip: "The limit is a ceiling; conditions can lower it." },
  { id: "ny_012", stateCode: "NY", topic: "speed_limits", difficulty: 1, question: "Unless posted otherwise, what is the speed limit in New York City?", options: ["20 mph", "25 mph", "30 mph", "35 mph"], correctIndex: 1, explanation: "New York City generally uses a 25 mph citywide speed limit unless signs show another limit. Drivers must still slow below that limit when conditions require.", rule: "VTL 1642 and NYC Traffic Rules - Speed Limits", tip: "NYC streets default to twenty-five." },
  { id: "ny_013", stateCode: "NY", topic: "speed_limits", difficulty: 2, question: "What should you do when approaching a curve, hillcrest, or narrow roadway?", options: ["Maintain the posted limit", "Reduce speed when the hazard makes it necessary", "Move toward the center line", "Use the horn and continue"], correctIndex: 1, explanation: "New York speed law requires appropriate reduced speed for curves, hillcrests, narrow roads, and other hazards. The safe speed depends on what you can see and control.", rule: "VTL 1180 - Speed Restrictions for Hazards", tip: "Less sight distance means less speed." },
  { id: "ny_014", stateCode: "NY", topic: "speed_limits", difficulty: 2, question: "What does New York law say about driving too slowly?", options: ["It is always legal because slower is safer", "You may not drive so slowly that you impede normal traffic", "It matters only on parkways", "It is legal with hazard lights on"], correctIndex: 1, explanation: "New York prohibits driving at such a slow speed as to impede normal and reasonable traffic movement. Exceptions apply when slower speed is necessary for safe operation or legal compliance.", rule: "VTL 1181 - Minimum Speed Regulations", tip: "Safe speed avoids both rushing and blocking." },
  { id: "ny_015", stateCode: "NY", topic: "speed_limits", difficulty: 2, question: "Near a school in New York, what should you expect?", options: ["The same speed limit always applies", "Lower posted school speed limits may apply during stated times", "Only buses must slow down", "School limits apply only on rural roads"], correctIndex: 1, explanation: "School speed limits may be posted for specific times, days, or conditions. Drivers must watch signs carefully and reduce speed for children and school activity.", rule: "VTL 1180 - School Speed Limits", tip: "School signs are time-sensitive, so read the whole sign." },
  { id: "ny_016", stateCode: "NY", topic: "dui_laws", difficulty: 1, question: "For most drivers in New York, what BAC is per se driving while intoxicated?", options: ["0.04 percent", "0.05 percent", "0.08 percent", "0.10 percent"], correctIndex: 2, explanation: "New York makes it illegal to operate a motor vehicle with a BAC of 0.08 percent or more. A driver can also violate the law at lower levels if alcohol impairs ability.", rule: "VTL 1192 - Driving While Intoxicated", tip: "Point-oh-eight is the per se line, but impairment can begin below it." },
  { id: "ny_017", stateCode: "NY", topic: "dui_laws", difficulty: 2, question: "What is Aggravated DWI in New York based on BAC?", options: ["0.10 percent or higher", "0.12 percent or higher", "0.15 percent or higher", "0.18 percent or higher"], correctIndex: 3, explanation: "New York has an aggravated DWI category for a BAC of 0.18 percent or more. This is a higher BAC threshold than ordinary per se DWI.", rule: "VTL 1192 - Aggravated Driving While Intoxicated", tip: "Aggravated DWI is the high-number warning: 0.18." },
  { id: "ny_018", stateCode: "NY", topic: "dui_laws", difficulty: 2, question: "What does New York's DWAI alcohol rule mean?", options: ["A driver may be charged when alcohol impairs ability even below 0.08", "Only drivers over 21 can be charged", "It applies only to commercial vehicles", "It requires a crash before police can act"], correctIndex: 0, explanation: "Driving while ability impaired by alcohol can apply when alcohol affects driving ability even below the 0.08 DWI threshold. New York treats impairment and the per se BAC limit as separate concepts.", rule: "VTL 1192 - Driving While Ability Impaired", tip: "Below 0.08 does not automatically mean legal." },
  { id: "ny_019", stateCode: "NY", topic: "dui_laws", difficulty: 2, question: "What is true about drugs and DWI-style offenses in New York?", options: ["Only illegal drugs count", "Prescription or illegal drugs can violate the law if they impair driving", "Drugs matter only if mixed with alcohol", "Medicine labels never affect driving legality"], correctIndex: 1, explanation: "New York prohibits driving while ability is impaired by drugs. A prescription does not make driving legal if the drug impairs safe operation.", rule: "VTL 1192 - Driving While Ability Impaired by Drugs", tip: "Legal medicine can still make illegal driving." },
  { id: "ny_020", stateCode: "NY", topic: "dui_laws", difficulty: 3, question: "What special New York DWI rule applies when a child passenger is in the vehicle?", options: ["The offense can become aggravated when a child 15 or younger is present", "The BAC limit changes to 0.10 percent", "Only the passenger receives a citation", "It applies only on school property"], correctIndex: 0, explanation: "New York law includes aggravated DWI provisions for driving intoxicated with a child passenger age 15 or younger. This reflects the added danger to a vulnerable passenger.", rule: "VTL 1192 - Aggravated DWI With a Child", tip: "A child passenger makes impaired driving even more serious." },
  { id: "ny_021", stateCode: "NY", topic: "road_markings", difficulty: 1, question: "What do double solid yellow lines generally mean?", options: ["Passing is allowed in both directions", "Do not cross to pass except where lawfully permitted", "Traffic on both sides moves the same direction", "The lane is for emergency vehicles"], correctIndex: 1, explanation: "Double solid yellow lines separate opposing traffic and generally prohibit crossing to pass. Drivers may cross only for lawful movements such as certain turns when safe and allowed.", rule: "VTL 1126 - No-Passing Zones; VTL 1110 - Traffic-Control Devices", tip: "Double yellow is a wall for passing." },
  { id: "ny_022", stateCode: "NY", topic: "road_markings", difficulty: 2, question: "What does a broken white lane line usually mean?", options: ["Lane changes may be made when safe", "No lane changes are allowed", "Traffic moves in opposite directions", "Only taxis may cross it"], correctIndex: 0, explanation: "Broken white lines separate lanes moving in the same direction. You may change lanes when it can be done safely and legally.", rule: "VTL 1128 - Driving on Roadways Laned for Traffic", tip: "Broken white permits a careful lane change." },
  { id: "ny_023", stateCode: "NY", topic: "road_markings", difficulty: 2, question: "What does New York law require on a roadway marked for lanes?", options: ["Drive as nearly as practical entirely within one lane", "Use two lanes when traffic is slow", "Change lanes without signaling in city traffic", "Follow lane lines only on highways"], correctIndex: 0, explanation: "A vehicle must be driven as nearly as practical entirely within a single lane. It should not be moved from that lane until the movement can be made safely.", rule: "VTL 1128 - Driving on Roadways Laned for Traffic", tip: "Stay in one lane until a safe change is ready." },
  { id: "ny_024", stateCode: "NY", topic: "road_markings", difficulty: 2, question: "In a marked bus lane in New York City, what should drivers expect?", options: ["Any driver may use it to pass", "Bus lane signs and markings restrict use to permitted vehicles and times", "It is open when taxis are not present", "It is only advisory paint"], correctIndex: 1, explanation: "NYC bus lanes are controlled by signs and pavement markings that limit when and how general traffic may use them. Drivers must read the posted restrictions because permitted times and turns vary.", rule: "VTL 1110 - Traffic-Control Devices; NYC Traffic Rules", tip: "Bus lane paint is a rule, not decoration." },
  { id: "ny_025", stateCode: "NY", topic: "road_markings", difficulty: 3, question: "What should you do with a painted bike lane next to your lane?", options: ["Drive in it whenever traffic is backed up", "Keep out except when legally crossing or turning with caution", "Use it as a loading zone", "Merge into it before every right turn without checking"], correctIndex: 1, explanation: "Bike lane markings reserve space for bicycle travel and must be obeyed as traffic-control markings. Drivers crossing or turning near a bike lane must use caution and yield when required.", rule: "VTL 1110 and 1128 - Markings and Lane Use", tip: "Bike lane means check twice before crossing." },
  { id: "ny_026", stateCode: "NY", topic: "highway_driving", difficulty: 1, question: "How closely may you follow another vehicle in New York?", options: ["As close as traffic allows", "Only as close as is reasonable and prudent", "One car length at every speed", "Two seconds only on expressways"], correctIndex: 1, explanation: "New York prohibits following more closely than is reasonable and prudent. Safe distance depends on speed, traffic, weather, and road conditions.", rule: "VTL 1129 - Following Too Closely", tip: "More speed or worse weather means more space." },
  { id: "ny_027", stateCode: "NY", topic: "highway_driving", difficulty: 2, question: "Before changing lanes on a New York expressway, what must you do?", options: ["Signal and move only when safe", "Move first so others see your intention", "Slow sharply in your lane", "Use the shoulder to build speed"], correctIndex: 0, explanation: "Drivers must stay in their lane and move only when the change can be made safely. Signaling gives warning but does not create a safe gap.", rule: "VTL 1128 and 1163 - Lane Use and Signals", tip: "Signal early, but move only after the space is real." },
  { id: "ny_028", stateCode: "NY", topic: "highway_driving", difficulty: 2, question: "What is New York's Move Over requirement for stopped emergency or hazard vehicles?", options: ["Move over safely or slow down when approaching covered vehicles", "Move over only for police cars", "Stop in your lane until the scene clears", "Maintain speed to avoid congestion"], correctIndex: 0, explanation: "New York requires drivers approaching certain stopped emergency, hazard, or service vehicles to move over when safe or slow down. The rule protects people working near live traffic.", rule: "VTL 1144-a - Operation of Vehicles When Approaching Parked, Stopped or Standing Authorized Emergency Vehicles", tip: "Lights on the shoulder mean make room or slow down." },
  { id: "ny_029", stateCode: "NY", topic: "highway_driving", difficulty: 2, question: "When must you use headlights in New York?", options: ["Only from midnight to sunrise", "From one-half hour after sunset to one-half hour before sunrise and when visibility is poor", "Only on highways", "Only when wipers are on high speed"], correctIndex: 1, explanation: "New York requires headlights during nighttime hours and when visibility is reduced. Headlights help other road users see you, not just help you see the road.", rule: "VTL 375 - Required Lighting", tip: "If visibility drops, turn the lights on." },
  { id: "ny_030", stateCode: "NY", topic: "highway_driving", difficulty: 3, question: "On a New York parkway, what should drivers remember?", options: ["Commercial vehicles may use any parkway", "Parkways often restrict commercial vehicles and have low bridges", "Stopping in travel lanes is allowed for sightseeing", "Lane markings are optional on parkways"], correctIndex: 1, explanation: "Many New York parkways restrict commercial vehicles and include low-clearance bridges. Drivers must obey posted restrictions and plan routes before entering.", rule: "VTL 1621 and Local Parkway Regulations - Restricted Highways", tip: "Parkway signs matter before the ramp, not after the bridge appears." },
  { id: "ny_031", stateCode: "NY", topic: "parking", difficulty: 1, question: "Where is parking prohibited in New York?", options: ["On a crosswalk", "Beside an unpainted curb", "In front of your residence", "On a street with no meter"], correctIndex: 0, explanation: "New York prohibits stopping, standing, or parking on a crosswalk. Crosswalks must stay clear for pedestrian movement and visibility.", rule: "VTL 1202 - Stopping, Standing, or Parking Prohibited", tip: "Crosswalks are walking lanes, not waiting lanes." },
  { id: "ny_032", stateCode: "NY", topic: "parking", difficulty: 1, question: "How should you park parallel to a curb on a two-way street?", options: ["Facing the direction of traffic with wheels close to the curb", "Facing either direction if space is tight", "At an angle unless signs prohibit it", "With left wheels next to the curb"], correctIndex: 0, explanation: "Vehicles parked on a two-way roadway should generally face the direction of traffic. Parking against traffic makes pulling out and visibility more dangerous.", rule: "VTL 1203 - Additional Parking Regulations", tip: "Park with the flow, not against it." },
  { id: "ny_033", stateCode: "NY", topic: "parking", difficulty: 2, question: "How close may you park to a fire hydrant in New York City unless signs or local rules allow otherwise?", options: ["No closer than 5 feet", "No closer than 10 feet", "No closer than 15 feet", "No closer than 20 feet"], correctIndex: 2, explanation: "NYC commonly requires drivers to keep at least 15 feet from a fire hydrant unless a licensed driver remains to move the vehicle in limited circumstances. Firefighters need rapid access to hydrants.", rule: "VTL 1202 and NYC Traffic Rules - Fire Hydrants", tip: "Hydrants need fifteen feet of breathing room." },
  { id: "ny_034", stateCode: "NY", topic: "parking", difficulty: 2, question: "What must you do with alternate-side parking signs in New York City?", options: ["Ignore them on streets without meters", "Follow posted days and times for street cleaning or restrictions", "Follow them only in winter", "Treat them as suggestions if traffic is light"], correctIndex: 1, explanation: "Alternate-side parking signs create enforceable restrictions by day and time. Drivers must read the entire sign because rules can change from block to block.", rule: "VTL 1110 and NYC Traffic Rules - Posted Parking Restrictions", tip: "In NYC, the whole parking sign matters." },
  { id: "ny_035", stateCode: "NY", topic: "parking", difficulty: 2, question: "May you park in front of a driveway in New York?", options: ["Yes, if you leave a note", "Yes, for less than five minutes", "No, blocking a driveway is prohibited", "Only if it is your own driveway"], correctIndex: 2, explanation: "Parking in front of a public or private driveway is prohibited unless a specific local exception applies. Blocking a driveway can prevent safe entry and exit.", rule: "VTL 1202 - Parking in Front of Driveway", tip: "Driveways are doors for vehicles; keep them open." },
  { id: "ny_036", stateCode: "NY", topic: "pedestrians", difficulty: 1, question: "At an unsignalized crosswalk in New York, what must a driver do for a pedestrian crossing the roadway?", options: ["Yield, slowing or stopping if needed", "Proceed if the pedestrian is walking slowly", "Honk to warn and continue", "Yield only if the pedestrian is in a marked crosswalk"], correctIndex: 0, explanation: "New York requires drivers to yield the right-of-way to pedestrians crossing in a crosswalk when traffic signals are not present or operating. Drivers must slow or stop if needed to yield.", rule: "VTL 1151 - Pedestrians' Right of Way in Crosswalks", tip: "In a crosswalk, expect to stop for the walker." },
  { id: "ny_037", stateCode: "NY", topic: "pedestrians", difficulty: 2, question: "A vehicle is stopped at a crosswalk for a pedestrian. What may you do?", options: ["Pass carefully if there is room", "Do not overtake and pass the stopped vehicle", "Pass only if you honk first", "Pass if the pedestrian is more than one lane away"], correctIndex: 1, explanation: "New York prohibits overtaking and passing a vehicle stopped at a crosswalk to let a pedestrian cross. The stopped vehicle may hide the pedestrian from view.", rule: "VTL 1151 - Passing Vehicle Stopped at Crosswalk", tip: "A stopped car at a crosswalk may be shielding a person." },
  { id: "ny_038", stateCode: "NY", topic: "pedestrians", difficulty: 2, question: "What must pedestrians do when crossing outside a crosswalk?", options: ["Yield to vehicles on the roadway", "Expect vehicles to stop immediately", "Cross only while facing traffic", "Cross only during daylight"], correctIndex: 0, explanation: "A pedestrian crossing outside a crosswalk must yield to vehicles. Drivers still must use care to avoid collisions with pedestrians.", rule: "VTL 1152 - Crossing at Other Than Crosswalks", tip: "Outside a crosswalk, pedestrians yield, but drivers still protect." },
  { id: "ny_039", stateCode: "NY", topic: "pedestrians", difficulty: 2, question: "In New York City, what should drivers expect at intersections with heavy pedestrian traffic?", options: ["Pedestrians have strong crossing protections and drivers must yield carefully", "Vehicles always go first on green", "Pedestrians must wait until all turning traffic clears", "Horns give drivers priority"], correctIndex: 0, explanation: "Turning drivers must yield to pedestrians lawfully in the crosswalk. NYC driving requires extra caution because dense pedestrian traffic can fill crosswalks quickly.", rule: "VTL 1111 and 1151 - Signals and Pedestrian Right-of-Way", tip: "Green lets you go only after pedestrians are safe." },
  { id: "ny_040", stateCode: "NY", topic: "pedestrians", difficulty: 3, question: "What is true when a pedestrian suddenly leaves the curb into a vehicle's path?", options: ["Drivers never need to brake", "Pedestrians may not suddenly enter when it is impractical for the driver to yield", "The pedestrian always has unlimited priority", "Only buses must yield"], correctIndex: 1, explanation: "New York pedestrian right-of-way law does not allow a pedestrian to suddenly leave a curb and enter the path of a vehicle so close that yielding is impractical. Drivers still must remain alert and use due care.", rule: "VTL 1151 - Pedestrian Duties in Crosswalks", tip: "Crosswalk rights still require safe timing." },
];

const newYorkBank: StateBank = {
  stateCode: "NY",
  stateName: "New York",
  questions,
};

export default newYorkBank;
