import type { StateBank, Topic } from "./types";

const questions: Array<{
  id: string;
  stateCode: string;
  topic: Topic;
  difficulty: 1 | 2 | 3;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  rule: string;
  tip: string;
}> = [
  {
    id: "tx_001",
    stateCode: "TX",
    topic: "traffic_signs",
    difficulty: 1,
    question: "What must you do at a Texas stop sign?",
    options: [
      "Slow down and continue if no traffic is close",
      "Stop completely at the marked line, crosswalk, or nearest point before entering",
      "Stop only if another vehicle arrives first",
      "Roll through if you can see clearly both ways",
    ],
    correctIndex: 1,
    explanation: "A stop sign requires a complete stop before entering the intersection. If there is no stop line or crosswalk, stop where you can safely view approaching traffic.",
    rule: "Texas Transportation Code 544.010 - Stop Signs and Yield Signs",
    tip: "Stop means the wheels stop, not just the speedometer dropping.",
  },
  {
    id: "tx_002",
    stateCode: "TX",
    topic: "traffic_signs",
    difficulty: 1,
    question: "At a steady red light in Texas, when may you turn right?",
    options: [
      "After stopping and yielding, unless a sign prohibits the turn",
      "Only when a green arrow appears",
      "Without stopping if the right lane is clear",
      "Only from a one-way street onto another one-way street",
    ],
    correctIndex: 0,
    explanation: "Texas requires a stop at a steady red signal before entering the intersection. A right turn after stopping is allowed unless a sign prohibits it and only after yielding to pedestrians and traffic.",
    rule: "Texas Transportation Code 544.007 - Traffic-Control Signals",
    tip: "Red lets you turn right only after stop, look, and yield.",
  },
  {
    id: "tx_003",
    stateCode: "TX",
    topic: "traffic_signs",
    difficulty: 2,
    question: "What does a flashing yellow signal mean at an intersection?",
    options: [
      "Stop and proceed only when all lanes are clear",
      "Proceed with caution",
      "The signal is for pedestrians only",
      "You have the same protection as a green arrow",
    ],
    correctIndex: 1,
    explanation: "A flashing yellow signal warns drivers to proceed carefully. It does not give protected right-of-way over other traffic or pedestrians.",
    rule: "Texas Transportation Code 544.007 - Flashing Signals",
    tip: "Yellow flashes say caution, not command.",
  },
  {
    id: "tx_004",
    stateCode: "TX",
    topic: "traffic_signs",
    difficulty: 2,
    question: "At a yield sign on a Texas frontage road ramp, what should you do?",
    options: [
      "Stop every time, even when the roadway is empty",
      "Accelerate because ramp traffic has priority",
      "Slow or stop as needed and yield to vehicles close enough to be a hazard",
      "Enter first if your vehicle is already partly in the lane",
    ],
    correctIndex: 2,
    explanation: "A yield sign requires slowing or stopping when necessary. You must yield to traffic that is close enough to create a hazard.",
    rule: "Texas Transportation Code 544.010 - Stop Signs and Yield Signs",
    tip: "Yield means your turn comes after the hazard clears.",
  },
  {
    id: "tx_005",
    stateCode: "TX",
    topic: "traffic_signs",
    difficulty: 2,
    question: "What is required when an official traffic-control device gives an instruction?",
    options: [
      "Follow it unless local traffic usually ignores it",
      "Follow it unless a police officer directs otherwise",
      "Follow it only if a warning sign is also posted",
      "Follow it only during daylight hours",
    ],
    correctIndex: 1,
    explanation: "Texas drivers must obey official traffic-control devices. A lawful direction from a police officer or authorized person can control over the posted device.",
    rule: "Texas Transportation Code 544.004 - Compliance With Traffic-Control Devices",
    tip: "Signs and signals set the rule unless an officer gives a new one.",
  },
  {
    id: "tx_006",
    stateCode: "TX",
    topic: "right_of_way",
    difficulty: 1,
    question: "Two vehicles arrive at an uncontrolled intersection from different roads at about the same time. Who yields?",
    options: [
      "The driver on the left yields to the driver on the right",
      "The driver on the right yields to the driver on the left",
      "The driver on the wider road always yields",
      "The driver going straight always yields",
    ],
    correctIndex: 0,
    explanation: "At an uncontrolled intersection, the driver on the left must yield to the vehicle on the immediate right. This rule gives drivers a predictable order when there is no sign or signal.",
    rule: "Texas Transportation Code 545.151 - Vehicle Approaching or Entering Intersection",
    tip: "Ties at intersections go to the right.",
  },
  {
    id: "tx_007",
    stateCode: "TX",
    topic: "right_of_way",
    difficulty: 2,
    question: "When turning left at an intersection in Texas, what must you do with oncoming traffic?",
    options: [
      "Turn first if your signal is on",
      "Yield to oncoming vehicles close enough to be a hazard",
      "Enter the intersection and make oncoming traffic stop",
      "Yield only if the oncoming vehicle is speeding",
    ],
    correctIndex: 1,
    explanation: "A driver turning left must yield to oncoming vehicles that are in the intersection or close enough to be an immediate hazard. Signaling does not give the turning driver priority.",
    rule: "Texas Transportation Code 545.152 - Vehicle Turning Left",
    tip: "Left turns wait for a safe opening.",
  },
  {
    id: "tx_008",
    stateCode: "TX",
    topic: "right_of_way",
    difficulty: 2,
    question: "You are entering a Texas road from a private driveway. What is your duty?",
    options: [
      "Yield to vehicles already on the roadway",
      "Enter slowly because driveway traffic has priority",
      "Stop only if a stop sign is posted",
      "Use your horn and proceed",
    ],
    correctIndex: 0,
    explanation: "A driver entering or crossing a highway from private property must yield to traffic on the highway. Roadway traffic should not have to make a sudden stop for a vehicle leaving a driveway.",
    rule: "Texas Transportation Code 545.155 - Vehicle Entering Highway From Private Road or Driveway",
    tip: "Driveway traffic waits for roadway traffic.",
  },
  {
    id: "tx_009",
    stateCode: "TX",
    topic: "right_of_way",
    difficulty: 2,
    question: "What should you do when an authorized emergency vehicle approaches with lights and siren?",
    options: [
      "Pull to the right edge or curb and stop until it passes",
      "Keep moving if you are already at the speed limit",
      "Stop in the center lane immediately",
      "Speed up to stay ahead of it",
    ],
    correctIndex: 0,
    explanation: "Texas drivers must yield the right-of-way to an emergency vehicle using audible and visual signals. Pull to the right edge or curb and stop until the vehicle has passed, unless directed otherwise.",
    rule: "Texas Transportation Code 545.156 - Vehicle Approached by Authorized Emergency Vehicle",
    tip: "Lights and siren mean right side and stop.",
  },
  {
    id: "tx_010",
    stateCode: "TX",
    topic: "right_of_way",
    difficulty: 3,
    question: "At a four-way stop, four vehicles arrive almost together. What is the safest legal approach?",
    options: [
      "The largest vehicle goes first",
      "The driver who stopped first goes first; same-time arrivals yield to the right",
      "The driver turning left always goes first",
      "All drivers should roll forward until one driver stops",
    ],
    correctIndex: 1,
    explanation: "Texas right-of-way rules favor the first vehicle to arrive, and same-time conflicts are resolved by yielding to the vehicle on the right. Drivers should communicate by position and patience, not by forcing the intersection.",
    rule: "Texas Transportation Code 545.151 - Intersection Right-of-Way",
    tip: "First arrival first; same-time tie goes right.",
  },
  {
    id: "tx_011",
    stateCode: "TX",
    topic: "speed_limits",
    difficulty: 1,
    question: "Unless a different limit is posted, what is the usual Texas daytime speed limit on a numbered highway outside an urban district?",
    options: [
      "55 mph",
      "60 mph",
      "70 mph",
      "75 mph",
    ],
    correctIndex: 2,
    explanation: "Texas law sets a 70 mph daytime limit for passenger cars on numbered highways outside urban districts unless otherwise posted. Drivers still must slow down when conditions make that speed unsafe.",
    rule: "Texas Transportation Code 545.352 - Prima Facie Speed Limits",
    tip: "Rural numbered highway in Texas: think seventy unless signs say otherwise.",
  },
  {
    id: "tx_012",
    stateCode: "TX",
    topic: "speed_limits",
    difficulty: 1,
    question: "What is Texas's basic speed rule?",
    options: [
      "Drive the posted limit no matter the conditions",
      "Never drive faster than is reasonable and prudent under the circumstances",
      "Always drive 10 mph below the posted limit in rain",
      "Match the speed of the fastest traffic around you",
    ],
    correctIndex: 1,
    explanation: "Texas requires drivers to control speed as necessary to avoid collisions and to drive at a careful and prudent speed. The posted limit is not safe if weather, traffic, or road conditions make it unsafe.",
    rule: "Texas Transportation Code 545.351 - Maximum Speed Requirement",
    tip: "The sign is a ceiling, not a promise that the road is safe.",
  },
  {
    id: "tx_013",
    stateCode: "TX",
    topic: "speed_limits",
    difficulty: 2,
    question: "Unless posted otherwise, what is the Texas prima facie speed limit in an urban district?",
    options: [
      "20 mph",
      "25 mph",
      "30 mph",
      "35 mph",
    ],
    correctIndex: 2,
    explanation: "Texas sets a 30 mph prima facie speed limit in urban districts unless a different limit is posted. A prima facie limit is presumed reasonable only when conditions are safe.",
    rule: "Texas Transportation Code 545.352 - Prima Facie Speed Limits",
    tip: "City streets commonly start at thirty in Texas.",
  },
  {
    id: "tx_014",
    stateCode: "TX",
    topic: "speed_limits",
    difficulty: 2,
    question: "When approaching a railroad crossing with limited visibility, what does Texas speed law expect?",
    options: [
      "Keep the posted speed until you see a train",
      "Reduce speed as needed to safely avoid a collision",
      "Stop only if the crossing arm is down",
      "Speed up to reduce time on the tracks",
    ],
    correctIndex: 1,
    explanation: "Texas requires drivers to reduce speed when approaching and crossing an intersection or railroad grade crossing when conditions require it. Limited visibility is a reason to slow before the hazard.",
    rule: "Texas Transportation Code 545.351 - Speed Reduced for Hazards",
    tip: "Tracks plus poor view means slow before you know.",
  },
  {
    id: "tx_015",
    stateCode: "TX",
    topic: "speed_limits",
    difficulty: 2,
    question: "What does Texas law say about driving too slowly?",
    options: [
      "It is always legal because slower is safer",
      "It is legal only with hazard lights on",
      "You may not drive so slowly that you impede normal and reasonable traffic",
      "It is illegal only on interstate highways",
    ],
    correctIndex: 2,
    explanation: "Texas prohibits driving so slowly that the driver impedes the normal and reasonable movement of traffic. This does not apply when reduced speed is necessary for safe operation or legal compliance.",
    rule: "Texas Transportation Code 545.363 - Minimum Speed Regulations",
    tip: "Safe speed means neither too fast nor needlessly too slow.",
  },
  {
    id: "tx_016",
    stateCode: "TX",
    topic: "dui_laws",
    difficulty: 1,
    question: "For most adult drivers in Texas, what alcohol concentration is legally intoxicated?",
    options: [
      "0.04 percent",
      "0.05 percent",
      "0.08 percent",
      "0.10 percent",
    ],
    correctIndex: 2,
    explanation: "Texas defines intoxication to include an alcohol concentration of 0.08 percent or more for most drivers. A person may also be intoxicated if alcohol, drugs, or another substance causes loss of normal mental or physical faculties.",
    rule: "Texas Penal Code 49.01 and 49.04 - Intoxication and DWI",
    tip: "Point-oh-eight is the number, but impairment can happen earlier.",
  },
  {
    id: "tx_017",
    stateCode: "TX",
    topic: "dui_laws",
    difficulty: 2,
    question: "For a commercial driver operating a commercial motor vehicle in Texas, what alcohol concentration can trigger disqualification?",
    options: [
      "0.02 percent",
      "0.04 percent",
      "0.08 percent",
      "0.10 percent",
    ],
    correctIndex: 1,
    explanation: "Commercial drivers are held to a stricter alcohol standard while operating commercial motor vehicles. An alcohol concentration of 0.04 percent can trigger commercial driving consequences.",
    rule: "Texas Transportation Code 522.081 and 522.101 - Commercial Driver Alcohol Violations",
    tip: "Commercial driving cuts the usual number in half: 0.04.",
  },
  {
    id: "tx_018",
    stateCode: "TX",
    topic: "dui_laws",
    difficulty: 2,
    question: "What is Texas's alcohol rule for a person under 21 operating a motor vehicle?",
    options: [
      "They may drive below 0.08 percent",
      "They may drive if they do not feel impaired",
      "They may not drive with any detectable amount of alcohol",
      "They may drive below 0.04 percent",
    ],
    correctIndex: 2,
    explanation: "Texas has a zero-tolerance rule for minors operating motor vehicles with any detectable amount of alcohol. This is stricter than the adult DWI alcohol concentration standard.",
    rule: "Texas Alcoholic Beverage Code 106.041 - Driving or Operating Watercraft Under the Influence by Minor",
    tip: "Under 21 in Texas means none detected.",
  },
  {
    id: "tx_019",
    stateCode: "TX",
    topic: "dui_laws",
    difficulty: 2,
    question: "May a driver in Texas have an open container of alcohol in the passenger area of a vehicle on a public highway?",
    options: [
      "Yes, if the driver is not drinking from it",
      "Yes, if it belongs to a passenger",
      "No, open containers are generally prohibited in the passenger area",
      "No, unless the driver is parked at a red light",
    ],
    correctIndex: 2,
    explanation: "Texas generally prohibits possessing an open container of alcohol in the passenger area of a motor vehicle on a public highway. The rule applies even if the driver is not legally intoxicated.",
    rule: "Texas Penal Code 49.031 - Possession of Alcoholic Beverage in Motor Vehicle",
    tip: "Open container plus public road is a problem before DWI begins.",
  },
  {
    id: "tx_020",
    stateCode: "TX",
    topic: "dui_laws",
    difficulty: 3,
    question: "Which statement about DWI in Texas is correct?",
    options: [
      "Only alcohol can lead to a DWI",
      "DWI can involve alcohol, drugs, or a combination that impairs normal faculties",
      "Prescription medicine can never lead to DWI",
      "A driver is safe from DWI if the BAC is below 0.08 percent",
    ],
    correctIndex: 1,
    explanation: "Texas DWI law covers intoxication from alcohol, drugs, controlled substances, or combinations of substances. A BAC below 0.08 percent does not prevent a DWI charge if the person has lost normal mental or physical faculties.",
    rule: "Texas Penal Code 49.01 and 49.04 - Intoxication and DWI",
    tip: "DWI is about impairment, not only the drink count.",
  },
  {
    id: "tx_021",
    stateCode: "TX",
    topic: "road_markings",
    difficulty: 1,
    question: "What does a solid yellow center line on your side of the road mean?",
    options: [
      "Passing is allowed if the road ahead is clear",
      "Passing is not allowed from your lane",
      "Traffic moves in the same direction on both sides",
      "The lane is reserved for buses",
    ],
    correctIndex: 1,
    explanation: "Yellow center lines separate traffic moving in opposite directions. A solid yellow line on your side means you should not cross it to pass.",
    rule: "Texas Transportation Code 544.004 - Traffic-Control Device Compliance",
    tip: "Solid yellow on your side says stay on your side.",
  },
  {
    id: "tx_022",
    stateCode: "TX",
    topic: "road_markings",
    difficulty: 2,
    question: "What does a broken white lane line normally mean?",
    options: [
      "Lane changes are allowed when safe",
      "Lane changes are prohibited",
      "Traffic on both sides moves in opposite directions",
      "Only motorcycles may cross the line",
    ],
    correctIndex: 0,
    explanation: "Broken white lines separate lanes moving in the same direction and generally allow lane changes. The driver must still ensure the movement can be made safely.",
    rule: "Texas Transportation Code 545.060 - Driving on Roadway Laned for Traffic",
    tip: "Broken white means change if safe and signaled.",
  },
  {
    id: "tx_023",
    stateCode: "TX",
    topic: "road_markings",
    difficulty: 2,
    question: "When driving on a roadway divided into marked lanes, what does Texas law require?",
    options: [
      "Drive as nearly as practical entirely within a single lane",
      "Straddle lanes while deciding where to turn",
      "Use any lane marking as a guide only",
      "Change lanes without signaling if traffic is light",
    ],
    correctIndex: 0,
    explanation: "Texas requires a vehicle to be driven as nearly as practical entirely within a single lane. A driver may not move from the lane until the movement can be made safely.",
    rule: "Texas Transportation Code 545.060 - Driving on Roadway Laned for Traffic",
    tip: "Pick a lane, stay in it, then change only when safe.",
  },
  {
    id: "tx_024",
    stateCode: "TX",
    topic: "road_markings",
    difficulty: 2,
    question: "What is the purpose of a center lane marked for left turns from both directions?",
    options: [
      "Passing slow traffic",
      "Preparing for and making left turns",
      "Driving during rush hour",
      "Parking while loading passengers",
    ],
    correctIndex: 1,
    explanation: "A two-way left-turn lane is intended for vehicles from either direction to prepare for left turns. It should not be used as a travel lane or passing lane.",
    rule: "Texas Transportation Code 545.060 and 544.004 - Lane Markings and Traffic-Control Devices",
    tip: "Center turn lane means turn, not travel.",
  },
  {
    id: "tx_025",
    stateCode: "TX",
    topic: "road_markings",
    difficulty: 3,
    question: "What should you do when pavement markings and a posted sign give lane-use instructions?",
    options: [
      "Follow whichever instruction is easier",
      "Obey the official sign or marking unless directed otherwise by an officer",
      "Ignore markings if traffic is light",
      "Follow markings only during business hours",
    ],
    correctIndex: 1,
    explanation: "Official signs and pavement markings are traffic-control devices in Texas. Drivers must obey them unless a lawful direction from an authorized person requires something different.",
    rule: "Texas Transportation Code 544.004 - Compliance With Traffic-Control Devices",
    tip: "Paint can be law when it is an official traffic marking.",
  },
  {
    id: "tx_026",
    stateCode: "TX",
    topic: "highway_driving",
    difficulty: 1,
    question: "On a Texas highway, how should you follow another vehicle?",
    options: [
      "Close enough that other drivers cannot merge between you",
      "At a reasonable and prudent distance for speed, traffic, and road conditions",
      "Exactly two car lengths at all speeds",
      "One second behind if the pavement is dry",
    ],
    correctIndex: 1,
    explanation: "Texas prohibits following another vehicle more closely than is reasonable and prudent. The safe distance changes with speed, traffic, weather, and road conditions.",
    rule: "Texas Transportation Code 545.062 - Following Distance",
    tip: "More speed or less grip means more gap.",
  },
  {
    id: "tx_027",
    stateCode: "TX",
    topic: "highway_driving",
    difficulty: 2,
    question: "What must you do before moving from one lane to another on a Texas freeway?",
    options: [
      "Signal and move only when the lane change can be made safely",
      "Move first, then signal to confirm the lane change",
      "Slow suddenly to make space",
      "Change lanes whenever another driver leaves a gap",
    ],
    correctIndex: 0,
    explanation: "Texas requires safe lane movement and signaling before turning or changing lanes when another vehicle may be affected. A signal does not replace checking mirrors and blind spots.",
    rule: "Texas Transportation Code 545.104 and 545.060 - Signaling and Lane Use",
    tip: "Signal tells; mirrors and blind spots decide.",
  },
  {
    id: "tx_028",
    stateCode: "TX",
    topic: "highway_driving",
    difficulty: 2,
    question: "What is required when approaching certain stopped emergency, tow, TxDOT, or utility vehicles with lights activated?",
    options: [
      "Move over or slow down as required by Texas law",
      "Maintain speed so traffic flow stays steady",
      "Stop in your lane until the worker waves you through",
      "Move over only for police vehicles",
    ],
    correctIndex: 0,
    explanation: "Texas move-over law requires drivers to vacate the lane nearest certain stopped vehicles if safe, or slow down if moving over is not possible. The rule protects emergency responders and roadside workers.",
    rule: "Texas Transportation Code 545.157 - Passing Certain Vehicles",
    tip: "Flashing lights roadside mean lane away or speed down.",
  },
  {
    id: "tx_029",
    stateCode: "TX",
    topic: "highway_driving",
    difficulty: 2,
    question: "During heavy rain on a Texas highway, when must you use headlamps?",
    options: [
      "Only after sunset",
      "When visibility is reduced so a person or vehicle is not clearly discernible at 1,000 feet",
      "Only if your windshield wipers are on high speed",
      "Only on interstate highways",
    ],
    correctIndex: 1,
    explanation: "Texas requires lighted headlamps at nighttime and when reduced visibility makes people or vehicles not clearly discernible at 1,000 feet. Rain that requires wipers often reduces visibility, so turning on headlights is the safe expected practice.",
    rule: "Texas Transportation Code 547.302 - Duty to Display Lights",
    tip: "If rain makes you hard to see, headlights help others see you.",
  },
  {
    id: "tx_030",
    stateCode: "TX",
    topic: "highway_driving",
    difficulty: 3,
    question: "When passing another vehicle on a two-lane Texas highway, what is generally required?",
    options: [
      "Pass to the left at a safe distance and return right only when safely clear",
      "Pass on the shoulder if the vehicle is moving slowly",
      "Pass on either side when your horn is used",
      "Return right immediately after your front bumper passes the other vehicle",
    ],
    correctIndex: 0,
    explanation: "Texas generally requires passing on the left at a safe distance. You should not return to the right side until safely clear of the vehicle being passed.",
    rule: "Texas Transportation Code 545.053 - Passing to the Left",
    tip: "Pass left, clear fully, then return.",
  },
  {
    id: "tx_031",
    stateCode: "TX",
    topic: "parking",
    difficulty: 1,
    question: "Where is parking prohibited in Texas?",
    options: [
      "On a crosswalk",
      "Beside an unpainted curb in a residential area",
      "In front of your own house",
      "On a street with no posted signs",
    ],
    correctIndex: 0,
    explanation: "Texas prohibits stopping, standing, or parking on a crosswalk. Crosswalks must remain clear so pedestrians can cross safely.",
    rule: "Texas Transportation Code 545.302 - Stopping, Standing, or Parking Prohibited in Certain Places",
    tip: "Crosswalks are for feet, not parked wheels.",
  },
  {
    id: "tx_032",
    stateCode: "TX",
    topic: "parking",
    difficulty: 1,
    question: "When parallel parking on a two-way street in Texas, how should your vehicle usually face?",
    options: [
      "Facing the direction of traffic on your side of the road",
      "Facing either direction if the street is wide",
      "Facing opposite traffic if your flashers are on",
      "At an angle unless signs prohibit it",
    ],
    correctIndex: 0,
    explanation: "A vehicle stopped or parked on a two-way roadway should generally be parallel to the curb and facing the direction of authorized traffic. Parking against traffic creates visibility and reentry hazards.",
    rule: "Texas Transportation Code 545.303 - Additional Parking Regulations",
    tip: "Park the way traffic flows.",
  },
  {
    id: "tx_033",
    stateCode: "TX",
    topic: "parking",
    difficulty: 2,
    question: "How close may you park to a fire hydrant in Texas unless allowed by local rule or direction?",
    options: [
      "No closer than 5 feet",
      "No closer than 10 feet",
      "No closer than 15 feet",
      "No closer than 20 feet",
    ],
    correctIndex: 2,
    explanation: "Texas prohibits parking within 15 feet of a fire hydrant. Fire crews need open access to connect hoses quickly.",
    rule: "Texas Transportation Code 545.302 - Parking Near Fire Hydrant",
    tip: "Hydrant space is fifteen feet of emergency room.",
  },
  {
    id: "tx_034",
    stateCode: "TX",
    topic: "parking",
    difficulty: 2,
    question: "What is required to park in an accessible parking space in Texas?",
    options: [
      "A proper disabled parking placard or license plate",
      "Only a note saying the driver will return soon",
      "Only a passenger who is over 65",
      "Permission from a nearby business",
    ],
    correctIndex: 0,
    explanation: "Accessible parking spaces are reserved for vehicles displaying the required disabled parking placard or license plate. The access aisle beside the space must also be kept clear.",
    rule: "Texas Transportation Code 681.011 - Offenses Related to Parking Placards and Plates",
    tip: "Accessible spaces need accessible parking authority.",
  },
  {
    id: "tx_035",
    stateCode: "TX",
    topic: "parking",
    difficulty: 2,
    question: "May you park in front of a public or private driveway in Texas?",
    options: [
      "Yes, if you stay inside the vehicle",
      "Yes, for less than five minutes",
      "No, parking in front of a driveway is prohibited",
      "No, unless it is after business hours",
    ],
    correctIndex: 2,
    explanation: "Texas prohibits stopping, standing, or parking in front of a public or private driveway. Blocking a driveway can trap vehicles or force unsafe movements.",
    rule: "Texas Transportation Code 545.302 - Parking in Front of Driveway",
    tip: "Driveways are exits, so keep them open.",
  },
  {
    id: "tx_036",
    stateCode: "TX",
    topic: "pedestrians",
    difficulty: 1,
    question: "When must a Texas driver yield to a pedestrian in a crosswalk at an intersection with no traffic signal?",
    options: [
      "When the pedestrian is on the driver's half of the roadway or close enough to be in danger",
      "Only when the pedestrian waves at the driver",
      "Only if the pedestrian is walking with a group",
      "Only after the pedestrian reaches the center line",
    ],
    correctIndex: 0,
    explanation: "Texas drivers must yield to pedestrians in a crosswalk when the pedestrian is on the driver's half of the roadway or approaching so closely from the opposite half as to be in danger. Drivers should slow or stop as needed.",
    rule: "Texas Transportation Code 552.003 - Pedestrian Right-of-Way at Crosswalk",
    tip: "If the pedestrian is in or near your path, yield.",
  },
  {
    id: "tx_037",
    stateCode: "TX",
    topic: "pedestrians",
    difficulty: 2,
    question: "A vehicle is stopped at a crosswalk for a pedestrian. What may another driver do?",
    options: [
      "Pass only if there is an open lane",
      "Pass slowly while honking",
      "Not pass the stopped vehicle",
      "Pass if the pedestrian is more than one lane away",
    ],
    correctIndex: 2,
    explanation: "Texas prohibits a driver from passing a vehicle stopped at a crosswalk to permit a pedestrian to cross. The stopped vehicle may block your view of the pedestrian.",
    rule: "Texas Transportation Code 552.003 - Passing Vehicle Stopped at Crosswalk",
    tip: "A stopped car at a crosswalk is a warning sign.",
  },
  {
    id: "tx_038",
    stateCode: "TX",
    topic: "pedestrians",
    difficulty: 2,
    question: "What must a pedestrian do when crossing outside a marked or unmarked crosswalk?",
    options: [
      "Yield the right-of-way to vehicles on the roadway",
      "Expect all traffic to stop immediately",
      "Cross only while facing traffic",
      "Cross only if wearing bright clothing",
    ],
    correctIndex: 0,
    explanation: "A pedestrian crossing outside a crosswalk must yield to vehicles on the roadway. Drivers still have a duty to exercise care to avoid hitting pedestrians.",
    rule: "Texas Transportation Code 552.005 - Crossing at Point Other Than Crosswalk",
    tip: "Outside the crosswalk, pedestrians yield, but drivers still watch.",
  },
  {
    id: "tx_039",
    stateCode: "TX",
    topic: "pedestrians",
    difficulty: 2,
    question: "Between two adjacent intersections with working traffic signals, where should a pedestrian cross?",
    options: [
      "Only in a marked crosswalk",
      "Anywhere if traffic is light",
      "At the midpoint if there is no median",
      "Anywhere after yielding to vehicles",
    ],
    correctIndex: 0,
    explanation: "Texas requires pedestrians between adjacent signalized intersections to cross only in a marked crosswalk. This rule makes crossings predictable in controlled traffic areas.",
    rule: "Texas Transportation Code 552.005 - Crossing Between Adjacent Intersections",
    tip: "Signal to signal means marked crosswalk only.",
  },
  {
    id: "tx_040",
    stateCode: "TX",
    topic: "pedestrians",
    difficulty: 3,
    question: "What duty does a driver have toward pedestrians even when the pedestrian must yield?",
    options: [
      "Use the horn and continue at the same speed",
      "Exercise due care to avoid colliding with the pedestrian",
      "Drive around the pedestrian on either side",
      "Stop only if the pedestrian is in a marked crosswalk",
    ],
    correctIndex: 1,
    explanation: "Texas requires drivers to exercise due care to avoid colliding with pedestrians on a roadway. This duty applies even when another rule requires the pedestrian to yield.",
    rule: "Texas Transportation Code 552.008 - Drivers to Exercise Due Care",
    tip: "Right-of-way never cancels the duty to avoid a crash.",
  },
];

const texasBank: StateBank = {
  stateCode: "TX",
  stateName: "Texas",
  questions,
};

export default texasBank;
